package com.saicone.rtag.util;

import org.bukkit.Material;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.TreeMap;

/**
 * Minecraft item material tags with associated MC version
 * and some aliases for bukkit {@link Material} compatibility.
 *
 * @author Rubenicos
 */
@SuppressWarnings("javadoc")
public enum ItemMaterialTag {

    ACACIA_BOAT(MC.V_1_9, "BOAT_ACACIA"),
    ACACIA_BUTTON(MC.V_1_13),
    ACACIA_CHEST_BOAT(MC.V_1_19),
    ACACIA_DOOR(MC.V_1_8, "ACACIA_DOOR_ITEM"),
    ACACIA_FENCE(MC.V_1_8),
    ACACIA_FENCE_GATE(MC.V_1_8),
    ACACIA_HANGING_SIGN(MC.V_1_19_3),
    ACACIA_LEAVES(MC.V_1_13, "LEAVES2", MC.V_1_8, "LEAVES_2"),
    ACACIA_LOG(MC.V_1_13, "LOG2", MC.V_1_8, "LOG_2"),
    ACACIA_PLANKS(MC.V_1_13, "PLANKS:4", MC.V_1_8, "WOOD"),
    ACACIA_PRESSURE_PLATE(MC.V_1_13),
    ACACIA_SAPLING(MC.V_1_13, "SAPLING:4", MC.V_1_8),
    ACACIA_SHELF(MC.V_1_21_9),
    ACACIA_SIGN(MC.V_1_14),
    ACACIA_SLAB(MC.V_1_13, "WOODEN_SLAB:4", MC.V_1_8, "WOOD_STEP"),
    ACACIA_STAIRS(MC.V_1_8),
    ACACIA_TRAPDOOR(MC.V_1_13),
    ACACIA_WOOD(MC.V_1_13, "LOG2:12", MC.V_1_8, "LOG_2"),
    ACTIVATOR_RAIL(MC.V_1_8),
    ALLAY_SPAWN_EGG(MC.V_1_19),
    ALLIUM(MC.V_1_13, "RED_FLOWER:2", MC.V_1_8, "RED_ROSE"),
    AMETHYST_BLOCK(MC.V_1_17),
    AMETHYST_CLUSTER(MC.V_1_17),
    AMETHYST_SHARD(MC.V_1_17),
    ANCIENT_DEBRIS(MC.V_1_16),
    ANDESITE(MC.V_1_13, "STONE:5", MC.V_1_8),
    ANDESITE_SLAB(MC.V_1_14),
    ANDESITE_STAIRS(MC.V_1_14),
    ANDESITE_WALL(MC.V_1_14),
    ANGLER_POTTERY_SHERD(MC.V_1_20),
    ANVIL(MC.V_1_8),
    APPLE(MC.V_1_8),
    ARCHER_POTTERY_SHERD(MC.V_1_20, "POTTERY_SHARD_ARCHER", MC.V_1_19_4),
    ARMADILLO_SCUTE(MC.V_1_20_5),
    ARMADILLO_SPAWN_EGG(MC.V_1_20_5),
    ARMOR_STAND(MC.V_1_8),
    ARMS_UP_POTTERY_SHERD(MC.V_1_20, "POTTERY_SHARD_ARMS_UP", MC.V_1_19_4),
    ARROW(MC.V_1_8),
    AXOLOTL_BUCKET(MC.V_1_17),
    AXOLOTL_SPAWN_EGG(MC.V_1_17),
    AZALEA(MC.V_1_17),
    AZALEA_LEAVES(MC.V_1_17),
    AZURE_BLUET(MC.V_1_13, "RED_FLOWER:3", MC.V_1_8, "RED_ROSE"),
    BAKED_POTATO(MC.V_1_8),
    BAMBOO(MC.V_1_14),
    BAMBOO_BLOCK(MC.V_1_19_3),
    BAMBOO_BUTTON(MC.V_1_19_3),
    BAMBOO_CHEST_RAFT(MC.V_1_19_3),
    BAMBOO_DOOR(MC.V_1_19_3),
    BAMBOO_FENCE(MC.V_1_19_3),
    BAMBOO_FENCE_GATE(MC.V_1_19_3),
    BAMBOO_HANGING_SIGN(MC.V_1_19_3),
    BAMBOO_MOSAIC(MC.V_1_19_3),
    BAMBOO_MOSAIC_SLAB(MC.V_1_19_3),
    BAMBOO_MOSAIC_STAIRS(MC.V_1_19_3),
    BAMBOO_PLANKS(MC.V_1_19_3),
    BAMBOO_PRESSURE_PLATE(MC.V_1_19_3),
    BAMBOO_RAFT(MC.V_1_19_3),
    BAMBOO_SHELF(MC.V_1_21_9),
    BAMBOO_SIGN(MC.V_1_19_3),
    BAMBOO_SLAB(MC.V_1_19_3),
    BAMBOO_STAIRS(MC.V_1_19_3),
    BAMBOO_TRAPDOOR(MC.V_1_19_3),
    BARREL(MC.V_1_14),
    BARRIER(MC.V_1_8),
    BASALT(MC.V_1_16),
    BAT_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Bat", MC.V_1_9, "SPAWN_EGG:65", MC.V_1_8, "MONSTER_EGG"),
    BEACON(MC.V_1_8),
    BEDROCK(MC.V_1_8),
    BEEF(MC.V_1_8, "RAW_BEEF"),
    BEEHIVE(MC.V_1_15),
    BEETROOT(MC.V_1_9),
    BEETROOT_SEEDS(MC.V_1_9),
    BEETROOT_SOUP(MC.V_1_9),
    BEE_NEST(MC.V_1_15),
    BEE_SPAWN_EGG(MC.V_1_15),
    BELL(MC.V_1_14),
    BIG_DRIPLEAF(MC.V_1_17),
    BIRCH_BOAT(MC.V_1_9, "BOAT_BIRCH"),
    BIRCH_BUTTON(MC.V_1_13),
    BIRCH_CHEST_BOAT(MC.V_1_19),
    BIRCH_DOOR(MC.V_1_8, "BIRCH_DOOR_ITEM"),
    BIRCH_FENCE(MC.V_1_8),
    BIRCH_FENCE_GATE(MC.V_1_8),
    BIRCH_HANGING_SIGN(MC.V_1_19_3),
    BIRCH_LEAVES(MC.V_1_13, "LEAVES:2", MC.V_1_8),
    BIRCH_LOG(MC.V_1_13, "LOG:2", MC.V_1_8),
    BIRCH_PLANKS(MC.V_1_13, "PLANKS:2", MC.V_1_8, "WOOD"),
    BIRCH_PRESSURE_PLATE(MC.V_1_13),
    BIRCH_SAPLING(MC.V_1_13, "SAPLING:2", MC.V_1_8),
    BIRCH_SHELF(MC.V_1_21_9),
    BIRCH_SIGN(MC.V_1_14),
    BIRCH_SLAB(MC.V_1_13, "WOODEN_SLAB:2", MC.V_1_8, "WOOD_STEP"),
    BIRCH_STAIRS(MC.V_1_8, "BIRCH_WOOD_STAIRS"),
    BIRCH_TRAPDOOR(MC.V_1_13),
    BIRCH_WOOD(MC.V_1_13, "LOG:14", MC.V_1_8),
    BLACKSTONE(MC.V_1_16),
    BLACKSTONE_SLAB(MC.V_1_16),
    BLACKSTONE_STAIRS(MC.V_1_16),
    BLACKSTONE_WALL(MC.V_1_16),
    BLACK_BANNER(MC.V_1_13, "BANNER", MC.V_1_8),
    BLACK_BED(MC.V_1_13, "BED:15", MC.V_1_12),
    BLACK_BUNDLE(MC.V_1_21_2),
    BLACK_CANDLE(MC.V_1_17),
    BLACK_CARPET(MC.V_1_13, "CARPET:15", MC.V_1_8),
    BLACK_CONCRETE(MC.V_1_13, "CONCRETE:15", MC.V_1_12),
    BLACK_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:15", MC.V_1_12),
    BLACK_DYE(MC.V_1_14, "INK_SAC", MC.V_1_13, "DYE", MC.V_1_8, "INK_SACK"),
    BLACK_GLAZED_TERRACOTTA(MC.V_1_12),
    BLACK_HARNESS(MC.V_1_21_6),
    BLACK_SHULKER_BOX(MC.V_1_11),
    BLACK_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:15", MC.V_1_8),
    BLACK_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:15", MC.V_1_8),
    BLACK_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:15", MC.V_1_8, "STAINED_CLAY"),
    BLACK_WOOL(MC.V_1_13, "WOOL:15", MC.V_1_8),
    BLADE_POTTERY_SHERD(MC.V_1_20),
    BLAST_FURNACE(MC.V_1_14),
    BLAZE_POWDER(MC.V_1_8),
    BLAZE_ROD(MC.V_1_8),
    BLAZE_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Blaze", MC.V_1_9, "SPAWN_EGG:61", MC.V_1_8, "MONSTER_EGG"),
    BLUE_BANNER(MC.V_1_13, "BANNER:4", MC.V_1_8),
    BLUE_BED(MC.V_1_13, "BED:11", MC.V_1_12),
    BLUE_BUNDLE(MC.V_1_21_2),
    BLUE_CANDLE(MC.V_1_17),
    BLUE_CARPET(MC.V_1_13, "CARPET:11", MC.V_1_8),
    BLUE_CONCRETE(MC.V_1_13, "CONCRETE:11", MC.V_1_12),
    BLUE_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:11", MC.V_1_12),
    BLUE_DYE(MC.V_1_14, "LAPIS_LAZULI", MC.V_1_13, "DYE:4", MC.V_1_8, "INK_SACK"),
    BLUE_EGG(MC.V_1_21_5),
    BLUE_GLAZED_TERRACOTTA(MC.V_1_12),
    BLUE_HARNESS(MC.V_1_21_6),
    BLUE_ICE(MC.V_1_13),
    BLUE_ORCHID(MC.V_1_13, "RED_FLOWER:1", MC.V_1_8, "RED_ROSE"),
    BLUE_SHULKER_BOX(MC.V_1_11),
    BLUE_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:11", MC.V_1_8),
    BLUE_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:11", MC.V_1_8),
    BLUE_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:11", MC.V_1_8, "STAINED_CLAY"),
    BLUE_WOOL(MC.V_1_13, "WOOL:11", MC.V_1_8),
    BOGGED_SPAWN_EGG(MC.V_1_20_5),
    BOLT_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_20_5),
    BONE(MC.V_1_8),
    BONE_BLOCK(MC.V_1_10),
    BONE_MEAL(MC.V_1_13),
    BOOK(MC.V_1_8),
    BOOKSHELF(MC.V_1_8),
    BORDURE_INDENTED_BANNER_PATTERN(MC.V_1_21_2),
    BOW(MC.V_1_8),
    BOWL(MC.V_1_8),
    BRAIN_CORAL(MC.V_1_13),
    BRAIN_CORAL_BLOCK(MC.V_1_13),
    BRAIN_CORAL_FAN(MC.V_1_13),
    BREAD(MC.V_1_8),
    BREEZE_ROD(MC.V_1_20_5),
    BREEZE_SPAWN_EGG(MC.V_1_20_3),
    BREWER_POTTERY_SHERD(MC.V_1_20),
    BREWING_STAND(MC.V_1_8, "BREWING_STAND_ITEM"),
    BRICK(MC.V_1_8, "CLAY_BRICK"),
    BRICKS(MC.V_1_13, "BRICK_BLOCK", MC.V_1_8, "BRICK"),
    BRICK_SLAB(MC.V_1_13, "STONE_SLAB:4", MC.V_1_8, "STEP"),
    BRICK_STAIRS(MC.V_1_8),
    BRICK_WALL(MC.V_1_14),
    BROWN_BANNER(MC.V_1_13, "BANNER:3", MC.V_1_8),
    BROWN_BED(MC.V_1_13, "BED:12", MC.V_1_12),
    BROWN_BUNDLE(MC.V_1_21_2),
    BROWN_CANDLE(MC.V_1_17),
    BROWN_CARPET(MC.V_1_13, "CARPET:12", MC.V_1_8),
    BROWN_CONCRETE(MC.V_1_13, "CONCRETE:12", MC.V_1_12),
    BROWN_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:12", MC.V_1_12),
    BROWN_DYE(MC.V_1_14, "COCOA_BEANS", MC.V_1_13, "DYE:3", MC.V_1_8, "INK_SACK"),
    BROWN_EGG(MC.V_1_21_5),
    BROWN_GLAZED_TERRACOTTA(MC.V_1_12),
    BROWN_HARNESS(MC.V_1_21_6),
    BROWN_MUSHROOM(MC.V_1_8),
    BROWN_MUSHROOM_BLOCK(MC.V_1_8, "HUGE_MUSHROOM_1"),
    BROWN_SHULKER_BOX(MC.V_1_11),
    BROWN_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:12", MC.V_1_8),
    BROWN_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:12", MC.V_1_8),
    BROWN_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:12", MC.V_1_8, "STAINED_CLAY"),
    BROWN_WOOL(MC.V_1_13, "WOOL:12", MC.V_1_8),
    BRUSH(MC.V_1_19_4),
    BUBBLE_CORAL(MC.V_1_13),
    BUBBLE_CORAL_BLOCK(MC.V_1_13),
    BUBBLE_CORAL_FAN(MC.V_1_13),
    BUCKET(MC.V_1_8),
    BUDDING_AMETHYST(MC.V_1_17),
    BUNDLE(MC.V_1_17),
    BURN_POTTERY_SHERD(MC.V_1_20),
    BUSH(MC.V_1_21_5),
    CACTUS(MC.V_1_8),
    CACTUS_FLOWER(MC.V_1_21_5),
    CAKE(MC.V_1_8),
    CALCITE(MC.V_1_17),
    CALIBRATED_SCULK_SENSOR(MC.V_1_20),
    CAMEL_HUSK_SPAWN_EGG(MC.V_1_21_11),
    CAMEL_SPAWN_EGG(MC.V_1_19_3),
    CAMPFIRE(MC.V_1_14),
    CANDLE(MC.V_1_17),
    CARROT(MC.V_1_8, "CARROT_ITEM"),
    CARROT_ON_A_STICK(MC.V_1_8, "CARROT_STICK"),
    CARTOGRAPHY_TABLE(MC.V_1_14),
    CARVED_PUMPKIN(MC.V_1_13, "PUMPKIN", MC.V_1_8),
    CAT_SPAWN_EGG(MC.V_1_14),
    CAULDRON(MC.V_1_8, "CAULDRON_ITEM"),
    CAVE_SPIDER_SPAWN_EGG(MC.V_1_13, Map.of("SPAWN_EGG=cave_spider", MC.V_1_11, "SPAWN_EGG=CaveSpider", MC.V_1_9, "SPAWN_EGG:59", MC.V_1_8), "MONSTER_EGG"),
    CHAINMAIL_BOOTS(MC.V_1_8),
    CHAINMAIL_CHESTPLATE(MC.V_1_8),
    CHAINMAIL_HELMET(MC.V_1_8),
    CHAINMAIL_LEGGINGS(MC.V_1_8),
    CHAIN_COMMAND_BLOCK(MC.V_1_9, "COMMAND_CHAIN"),
    CHARCOAL(MC.V_1_13, "COAL:1", MC.V_1_8),
    CHERRY_BOAT(MC.V_1_19_4),
    CHERRY_BUTTON(MC.V_1_19_4),
    CHERRY_CHEST_BOAT(MC.V_1_19_4),
    CHERRY_DOOR(MC.V_1_19_4),
    CHERRY_FENCE(MC.V_1_19_4),
    CHERRY_FENCE_GATE(MC.V_1_19_4),
    CHERRY_HANGING_SIGN(MC.V_1_19_4),
    CHERRY_LEAVES(MC.V_1_19_4),
    CHERRY_LOG(MC.V_1_19_4),
    CHERRY_PLANKS(MC.V_1_19_4),
    CHERRY_PRESSURE_PLATE(MC.V_1_19_4),
    CHERRY_SAPLING(MC.V_1_19_4),
    CHERRY_SHELF(MC.V_1_21_9),
    CHERRY_SIGN(MC.V_1_19_4),
    CHERRY_SLAB(MC.V_1_19_4),
    CHERRY_STAIRS(MC.V_1_19_4),
    CHERRY_TRAPDOOR(MC.V_1_19_4),
    CHERRY_WOOD(MC.V_1_19_4),
    CHEST(MC.V_1_8),
    CHEST_MINECART(MC.V_1_8, "STORAGE_MINECART"),
    CHICKEN(MC.V_1_8, "RAW_CHICKEN"),
    CHICKEN_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Chicken", MC.V_1_9, "SPAWN_EGG:93", MC.V_1_8, "MONSTER_EGG"),
    CHIPPED_ANVIL(MC.V_1_13, "ANVIL:1", MC.V_1_8),
    CHISELED_BOOKSHELF(MC.V_1_19_3),
    CHISELED_COPPER(MC.V_1_20_3),
    CHISELED_DEEPSLATE(MC.V_1_17),
    CHISELED_NETHER_BRICKS(MC.V_1_16),
    CHISELED_POLISHED_BLACKSTONE(MC.V_1_16),
    CHISELED_QUARTZ_BLOCK(MC.V_1_13, "QUARTZ_BLOCK:1", MC.V_1_8),
    CHISELED_RED_SANDSTONE(MC.V_1_13, "RED_SANDSTONE:1", MC.V_1_8),
    CHISELED_RESIN_BRICKS(MC.V_1_21_4),
    CHISELED_SANDSTONE(MC.V_1_13, "SANDSTONE:1", MC.V_1_8),
    CHISELED_STONE_BRICKS(MC.V_1_13, "STONEBRICK:3", MC.V_1_8, "SMOOTH_BRICK"),
    CHISELED_TUFF(MC.V_1_20_3),
    CHISELED_TUFF_BRICKS(MC.V_1_20_3),
    CHORUS_FLOWER(MC.V_1_9),
    CHORUS_FRUIT(MC.V_1_9),
    CHORUS_PLANT(MC.V_1_9),
    CLAY(MC.V_1_8),
    CLAY_BALL(MC.V_1_8),
    CLOCK(MC.V_1_8, "WATCH"),
    CLOSED_EYEBLOSSOM(MC.V_1_21_4),
    COAL(MC.V_1_8),
    COAL_BLOCK(MC.V_1_8),
    COAL_ORE(MC.V_1_8),
    COARSE_DIRT(MC.V_1_13, "DIRT:1", MC.V_1_8),
    COAST_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_19_4),
    COBBLED_DEEPSLATE(MC.V_1_17),
    COBBLED_DEEPSLATE_SLAB(MC.V_1_17),
    COBBLED_DEEPSLATE_STAIRS(MC.V_1_17),
    COBBLED_DEEPSLATE_WALL(MC.V_1_17),
    COBBLESTONE(MC.V_1_8),
    COBBLESTONE_SLAB(MC.V_1_13, "STONE_SLAB:3", MC.V_1_8, "STEP"),
    // "COBBLESTONE_STAIRS" is an alias on legacy versions
    COBBLESTONE_STAIRS(MC.V_1_13, "STONE_STAIRS", MC.V_1_8),
    COBBLESTONE_WALL(MC.V_1_8, "COBBLE_WALL"),
    COBWEB(MC.V_1_13, "WEB", MC.V_1_8),
    COCOA_BEANS(MC.V_1_13),
    COD(MC.V_1_13, "FISH", MC.V_1_8, "RAW_FISH"),
    COD_BUCKET(MC.V_1_13),
    COD_SPAWN_EGG(MC.V_1_13),
    COMMAND_BLOCK(MC.V_1_8, "COMMAND"),
    COMMAND_BLOCK_MINECART(MC.V_1_8, "COMMAND_MINECART"),
    COMPARATOR(MC.V_1_8, "REDSTONE_COMPARATOR"),
    COMPASS(MC.V_1_8),
    COMPOSTER(MC.V_1_14),
    CONDUIT(MC.V_1_13),
    COOKED_BEEF(MC.V_1_8),
    COOKED_CHICKEN(MC.V_1_8),
    COOKED_COD(MC.V_1_13, "COOKED_FISH", MC.V_1_8),
    COOKED_MUTTON(MC.V_1_8),
    COOKED_PORKCHOP(MC.V_1_8, "GRILLED_PORK"),
    COOKED_RABBIT(MC.V_1_8),
    COOKED_SALMON(MC.V_1_13, "COOKED_FISH:1", MC.V_1_8),
    COOKIE(MC.V_1_8),
    COPPER_AXE(MC.V_1_21_9),
    COPPER_BARS(MC.V_1_21_9),
    COPPER_BLOCK(MC.V_1_17),
    COPPER_BOOTS(MC.V_1_21_9),
    COPPER_BULB(MC.V_1_20_3),
    COPPER_CHAIN(MC.V_1_21_9),
    COPPER_CHEST(MC.V_1_21_9),
    COPPER_CHESTPLATE(MC.V_1_21_9),
    COPPER_DOOR(MC.V_1_20_3),
    COPPER_GOLEM_SPAWN_EGG(MC.V_1_21_9),
    COPPER_GOLEM_STATUE(MC.V_1_21_9),
    COPPER_GRATE(MC.V_1_20_3),
    COPPER_HELMET(MC.V_1_21_9),
    COPPER_HOE(MC.V_1_21_9),
    COPPER_HORSE_ARMOR(MC.V_1_21_9),
    COPPER_INGOT(MC.V_1_17),
    COPPER_LANTERN(MC.V_1_21_9),
    COPPER_LEGGINGS(MC.V_1_21_9),
    COPPER_NAUTILUS_ARMOR(MC.V_1_21_11),
    COPPER_NUGGET(MC.V_1_21_9),
    COPPER_ORE(MC.V_1_17),
    COPPER_PICKAXE(MC.V_1_21_9),
    COPPER_SHOVEL(MC.V_1_21_9),
    COPPER_SPEAR(MC.V_1_21_11),
    COPPER_SWORD(MC.V_1_21_9),
    COPPER_TORCH(MC.V_1_21_9),
    COPPER_TRAPDOOR(MC.V_1_20_3),
    CORNFLOWER(MC.V_1_14),
    COW_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Cow", MC.V_1_9, "SPAWN_EGG:92", MC.V_1_8, "MONSTER_EGG"),
    CRACKED_DEEPSLATE_BRICKS(MC.V_1_17),
    CRACKED_DEEPSLATE_TILES(MC.V_1_17),
    CRACKED_NETHER_BRICKS(MC.V_1_16),
    CRACKED_POLISHED_BLACKSTONE_BRICKS(MC.V_1_16),
    CRACKED_STONE_BRICKS(MC.V_1_13, "STONEBRICK:2", MC.V_1_8, "SMOOTH_BRICK"),
    CRAFTER(MC.V_1_20_3),
    CRAFTING_TABLE(MC.V_1_8, "WORKBENCH"),
    CREAKING_HEART(MC.V_1_21_2),
    CREAKING_SPAWN_EGG(MC.V_1_21_2),
    CREEPER_BANNER_PATTERN(MC.V_1_14),
    CREEPER_HEAD(MC.V_1_13, "SKULL:4", MC.V_1_8, "SKULL_ITEM"),
    CREEPER_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Creeper", MC.V_1_9, "SPAWN_EGG:50", MC.V_1_8, "MONSTER_EGG"),
    CRIMSON_BUTTON(MC.V_1_16),
    CRIMSON_DOOR(MC.V_1_16),
    CRIMSON_FENCE(MC.V_1_16),
    CRIMSON_FENCE_GATE(MC.V_1_16),
    CRIMSON_FUNGUS(MC.V_1_16),
    CRIMSON_HANGING_SIGN(MC.V_1_19_3),
    CRIMSON_HYPHAE(MC.V_1_16),
    CRIMSON_NYLIUM(MC.V_1_16),
    CRIMSON_PLANKS(MC.V_1_16),
    CRIMSON_PRESSURE_PLATE(MC.V_1_16),
    CRIMSON_ROOTS(MC.V_1_16),
    CRIMSON_SHELF(MC.V_1_21_9),
    CRIMSON_SIGN(MC.V_1_16),
    CRIMSON_SLAB(MC.V_1_16),
    CRIMSON_STAIRS(MC.V_1_16),
    CRIMSON_STEM(MC.V_1_16),
    CRIMSON_TRAPDOOR(MC.V_1_16),
    CROSSBOW(MC.V_1_14),
    CRYING_OBSIDIAN(MC.V_1_16),
    CUT_COPPER(MC.V_1_17),
    CUT_COPPER_SLAB(MC.V_1_17),
    CUT_COPPER_STAIRS(MC.V_1_17),
    CUT_RED_SANDSTONE(MC.V_1_13),
    CUT_RED_SANDSTONE_SLAB(MC.V_1_14),
    CUT_SANDSTONE(MC.V_1_13),
    CUT_SANDSTONE_SLAB(MC.V_1_14),
    CYAN_BANNER(MC.V_1_13, "BANNER:6", MC.V_1_8),
    CYAN_BED(MC.V_1_13, "BED:9", MC.V_1_12),
    CYAN_BUNDLE(MC.V_1_21_2),
    CYAN_CANDLE(MC.V_1_17),
    CYAN_CARPET(MC.V_1_13, "CARPET:9", MC.V_1_8),
    CYAN_CONCRETE(MC.V_1_13, "CONCRETE:9", MC.V_1_12),
    CYAN_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:9", MC.V_1_12),
    CYAN_DYE(MC.V_1_13, "DYE:6", MC.V_1_8, "INK_SACK"),
    CYAN_GLAZED_TERRACOTTA(MC.V_1_12),
    CYAN_HARNESS(MC.V_1_21_6),
    CYAN_SHULKER_BOX(MC.V_1_11),
    CYAN_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:9", MC.V_1_8),
    CYAN_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:9", MC.V_1_8),
    CYAN_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:9", MC.V_1_8, "STAINED_CLAY"),
    CYAN_WOOL(MC.V_1_13, "WOOL:9", MC.V_1_8),
    DAMAGED_ANVIL(MC.V_1_13, "ANVIL:2", MC.V_1_8),
    DANDELION(MC.V_1_13, "YELLOW_FLOWER", MC.V_1_8),
    DANGER_POTTERY_SHERD(MC.V_1_20),
    DARK_OAK_BOAT(MC.V_1_9, "BOAT_DARK_OAK"),
    DARK_OAK_BUTTON(MC.V_1_13),
    DARK_OAK_CHEST_BOAT(MC.V_1_19),
    DARK_OAK_DOOR(MC.V_1_8, "DARK_OAK_DOOR_ITEM"),
    DARK_OAK_FENCE(MC.V_1_8),
    DARK_OAK_FENCE_GATE(MC.V_1_8),
    DARK_OAK_HANGING_SIGN(MC.V_1_19_3),
    DARK_OAK_LEAVES(MC.V_1_13, "LEAVES2:1", MC.V_1_8, "LEAVES_2"),
    DARK_OAK_LOG(MC.V_1_13, "LOG2:1", MC.V_1_8, "LOG_2"),
    DARK_OAK_PLANKS(MC.V_1_13, "PLANKS:5", MC.V_1_8, "WOOD"),
    DARK_OAK_PRESSURE_PLATE(MC.V_1_13),
    DARK_OAK_SAPLING(MC.V_1_13, "SAPLING:5", MC.V_1_8),
    DARK_OAK_SHELF(MC.V_1_21_9),
    DARK_OAK_SIGN(MC.V_1_14),
    DARK_OAK_SLAB(MC.V_1_13, "WOODEN_SLAB:5", MC.V_1_8, "WOOD_STEP"),
    DARK_OAK_STAIRS(MC.V_1_8),
    DARK_OAK_TRAPDOOR(MC.V_1_13),
    DARK_OAK_WOOD(MC.V_1_13, "LOG2:13", MC.V_1_8, "LOG_2"),
    DARK_PRISMARINE(MC.V_1_13, "PRISMARINE:2", MC.V_1_8),
    DARK_PRISMARINE_SLAB(MC.V_1_13),
    DARK_PRISMARINE_STAIRS(MC.V_1_13),
    DAYLIGHT_DETECTOR(MC.V_1_8),
    DEAD_BRAIN_CORAL(MC.V_1_13),
    DEAD_BRAIN_CORAL_BLOCK(MC.V_1_13),
    DEAD_BRAIN_CORAL_FAN(MC.V_1_13),
    DEAD_BUBBLE_CORAL(MC.V_1_13),
    DEAD_BUBBLE_CORAL_BLOCK(MC.V_1_13),
    DEAD_BUBBLE_CORAL_FAN(MC.V_1_13),
    // "DEAD_BUSH" is an alias on legacy versions
    // Legacy versions can translate "DEAD_BUSH" to "TALLGRASS:0"
    DEAD_BUSH(MC.V_1_13, "DEADBUSH", MC.V_1_8, "LONG_GRASS"),
    DEAD_FIRE_CORAL(MC.V_1_13),
    DEAD_FIRE_CORAL_BLOCK(MC.V_1_13),
    DEAD_FIRE_CORAL_FAN(MC.V_1_13),
    DEAD_HORN_CORAL(MC.V_1_13),
    DEAD_HORN_CORAL_BLOCK(MC.V_1_13),
    DEAD_HORN_CORAL_FAN(MC.V_1_13),
    DEAD_TUBE_CORAL(MC.V_1_13),
    DEAD_TUBE_CORAL_BLOCK(MC.V_1_13),
    DEAD_TUBE_CORAL_FAN(MC.V_1_13),
    DEBUG_STICK(MC.V_1_13),
    DECORATED_POT(MC.V_1_19_4),
    DEEPSLATE(MC.V_1_17),
    DEEPSLATE_BRICKS(MC.V_1_17),
    DEEPSLATE_BRICK_SLAB(MC.V_1_17),
    DEEPSLATE_BRICK_STAIRS(MC.V_1_17),
    DEEPSLATE_BRICK_WALL(MC.V_1_17),
    DEEPSLATE_COAL_ORE(MC.V_1_17),
    DEEPSLATE_COPPER_ORE(MC.V_1_17),
    DEEPSLATE_DIAMOND_ORE(MC.V_1_17),
    DEEPSLATE_EMERALD_ORE(MC.V_1_17),
    DEEPSLATE_GOLD_ORE(MC.V_1_17),
    DEEPSLATE_IRON_ORE(MC.V_1_17),
    DEEPSLATE_LAPIS_ORE(MC.V_1_17),
    DEEPSLATE_REDSTONE_ORE(MC.V_1_17),
    DEEPSLATE_TILES(MC.V_1_17),
    DEEPSLATE_TILE_SLAB(MC.V_1_17),
    DEEPSLATE_TILE_STAIRS(MC.V_1_17),
    DEEPSLATE_TILE_WALL(MC.V_1_17),
    DETECTOR_RAIL(MC.V_1_8),
    DIAMOND(MC.V_1_8),
    DIAMOND_AXE(MC.V_1_8),
    DIAMOND_BLOCK(MC.V_1_8),
    DIAMOND_BOOTS(MC.V_1_8),
    DIAMOND_CHESTPLATE(MC.V_1_8),
    DIAMOND_HELMET(MC.V_1_8),
    DIAMOND_HOE(MC.V_1_8),
    DIAMOND_HORSE_ARMOR(MC.V_1_8, "DIAMOND_BARDING"),
    DIAMOND_LEGGINGS(MC.V_1_8),
    DIAMOND_NAUTILUS_ARMOR(MC.V_1_21_11),
    DIAMOND_ORE(MC.V_1_8),
    DIAMOND_PICKAXE(MC.V_1_8),
    DIAMOND_SHOVEL(MC.V_1_8, "DIAMOND_SPADE"),
    DIAMOND_SPEAR(MC.V_1_21_11),
    DIAMOND_SWORD(MC.V_1_8),
    DIORITE(MC.V_1_13, "STONE:3", MC.V_1_8),
    DIORITE_SLAB(MC.V_1_14),
    DIORITE_STAIRS(MC.V_1_14),
    DIORITE_WALL(MC.V_1_14),
    DIRT(MC.V_1_8),
    DIRT_PATH(MC.V_1_17, "GRASS_PATH", MC.V_1_9),
    DISC_FRAGMENT_5(MC.V_1_19),
    DISPENSER(MC.V_1_8),
    DOLPHIN_SPAWN_EGG(MC.V_1_13),
    DONKEY_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=donkey", MC.V_1_11, "MONSTER_EGG"),
    DRAGON_BREATH(MC.V_1_9, "DRAGONS_BREATH"),
    DRAGON_EGG(MC.V_1_8),
    DRAGON_HEAD(MC.V_1_13, "SKULL:5", MC.V_1_8, "SKULL_ITEM"),
    DRIED_GHAST(MC.V_1_21_6),
    DRIED_KELP(MC.V_1_13),
    DRIED_KELP_BLOCK(MC.V_1_13),
    DRIPSTONE_BLOCK(MC.V_1_17),
    DROPPER(MC.V_1_8),
    DROWNED_SPAWN_EGG(MC.V_1_13),
    DUNE_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_19_4),
    ECHO_SHARD(MC.V_1_19),
    EGG(MC.V_1_8),
    ELDER_GUARDIAN_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=elder_guardian", MC.V_1_11, "MONSTER_EGG"),
    ELYTRA(MC.V_1_9),
    EMERALD(MC.V_1_8),
    EMERALD_BLOCK(MC.V_1_8),
    EMERALD_ORE(MC.V_1_8),
    ENCHANTED_BOOK(MC.V_1_8),
    ENCHANTED_GOLDEN_APPLE(MC.V_1_13, "GOLDEN_APPLE:1", MC.V_1_8),
    ENCHANTING_TABLE(MC.V_1_8, "ENCHANTMENT_TABLE"),
    ENDERMAN_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Enderman", MC.V_1_9, "SPAWN_EGG:58", MC.V_1_8, "MONSTER_EGG"),
    ENDERMITE_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Endermite", MC.V_1_9, "SPAWN_EGG:67", MC.V_1_8, "MONSTER_EGG"),
    ENDER_CHEST(MC.V_1_8),
    ENDER_DRAGON_SPAWN_EGG(MC.V_1_19_3),
    ENDER_EYE(MC.V_1_8, "EYE_OF_ENDER"),
    ENDER_PEARL(MC.V_1_8),
    END_CRYSTAL(MC.V_1_9),
    END_PORTAL_FRAME(MC.V_1_8, "ENDER_PORTAL_FRAME"),
    END_ROD(MC.V_1_9),
    END_STONE(MC.V_1_8, "ENDER_STONE"),
    END_STONE_BRICKS(MC.V_1_13, "END_BRICKS", MC.V_1_9),
    END_STONE_BRICK_SLAB(MC.V_1_14),
    END_STONE_BRICK_STAIRS(MC.V_1_14),
    END_STONE_BRICK_WALL(MC.V_1_14),
    EVOKER_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=evocation_illager", MC.V_1_11, "MONSTER_EGG"),
    EXPERIENCE_BOTTLE(MC.V_1_8, "EXP_BOTTLE"),
    EXPLORER_POTTERY_SHERD(MC.V_1_20),
    EXPOSED_CHISELED_COPPER(MC.V_1_20_3),
    EXPOSED_COPPER(MC.V_1_17),
    EXPOSED_COPPER_BARS(MC.V_1_21_9),
    EXPOSED_COPPER_BULB(MC.V_1_20_3),
    EXPOSED_COPPER_CHAIN(MC.V_1_21_9),
    EXPOSED_COPPER_CHEST(MC.V_1_21_9),
    EXPOSED_COPPER_DOOR(MC.V_1_20_3),
    EXPOSED_COPPER_GOLEM_STATUE(MC.V_1_21_9),
    EXPOSED_COPPER_GRATE(MC.V_1_20_3),
    EXPOSED_COPPER_LANTERN(MC.V_1_21_9),
    EXPOSED_COPPER_TRAPDOOR(MC.V_1_20_3),
    EXPOSED_CUT_COPPER(MC.V_1_17),
    EXPOSED_CUT_COPPER_SLAB(MC.V_1_17),
    EXPOSED_CUT_COPPER_STAIRS(MC.V_1_17),
    EXPOSED_LIGHTNING_ROD(MC.V_1_21_9),
    EYE_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_19_4),
    FARMLAND(MC.V_1_8, "SOIL"),
    FEATHER(MC.V_1_8),
    FERMENTED_SPIDER_EYE(MC.V_1_8),
    FERN(MC.V_1_13, "TALLGRASS:2", MC.V_1_8, "LONG_GRASS"),
    FIELD_MASONED_BANNER_PATTERN(MC.V_1_21_2),
    FILLED_MAP(MC.V_1_8, "MAP"),
    FIREFLY_BUSH(MC.V_1_21_5),
    FIREWORK_ROCKET(MC.V_1_13, "FIREWORKS", MC.V_1_8, "FIREWORK"),
    FIREWORK_STAR(MC.V_1_13, "FIREWORK_CHARGE", MC.V_1_8),
    FIRE_CHARGE(MC.V_1_8, "FIREBALL"),
    FIRE_CORAL(MC.V_1_13),
    FIRE_CORAL_BLOCK(MC.V_1_13),
    FIRE_CORAL_FAN(MC.V_1_13),
    FISHING_ROD(MC.V_1_8),
    FLETCHING_TABLE(MC.V_1_14),
    FLINT(MC.V_1_8),
    FLINT_AND_STEEL(MC.V_1_8),
    FLOWERING_AZALEA(MC.V_1_17),
    FLOWERING_AZALEA_LEAVES(MC.V_1_17),
    FLOWER_BANNER_PATTERN(MC.V_1_14),
    FLOWER_POT(MC.V_1_8, "FLOWER_POT_ITEM"),
    FLOW_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_20_5),
    FLOW_BANNER_PATTERN(MC.V_1_20_5),
    FLOW_POTTERY_SHERD(MC.V_1_20_5),
    FOX_SPAWN_EGG(MC.V_1_14),
    FRIEND_POTTERY_SHERD(MC.V_1_20),
    FROGSPAWN(MC.V_1_19),
    FROG_SPAWN_EGG(MC.V_1_19),
    FURNACE(MC.V_1_8),
    FURNACE_MINECART(MC.V_1_8, "POWERED_MINECART"),
    GHAST_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Ghast", MC.V_1_9, "SPAWN_EGG:56", MC.V_1_8, "MONSTER_EGG"),
    GHAST_TEAR(MC.V_1_8),
    GILDED_BLACKSTONE(MC.V_1_16),
    GLASS(MC.V_1_8),
    GLASS_BOTTLE(MC.V_1_8),
    GLASS_PANE(MC.V_1_8, "THIN_GLASS"),
    GLISTERING_MELON_SLICE(MC.V_1_13, "SPECKLED_MELON", MC.V_1_8),
    GLOBE_BANNER_PATTERN(MC.V_1_14),
    GLOWSTONE(MC.V_1_8),
    GLOWSTONE_DUST(MC.V_1_8),
    GLOW_BERRIES(MC.V_1_17),
    GLOW_INK_SAC(MC.V_1_17),
    GLOW_ITEM_FRAME(MC.V_1_17),
    GLOW_LICHEN(MC.V_1_17),
    GLOW_SQUID_SPAWN_EGG(MC.V_1_17),
    GOAT_HORN(MC.V_1_19),
    GOAT_SPAWN_EGG(MC.V_1_17),
    GOLDEN_APPLE(MC.V_1_8),
    GOLDEN_AXE(MC.V_1_8, "GOLD_AXE"),
    GOLDEN_BOOTS(MC.V_1_8, "GOLD_BOOTS"),
    GOLDEN_CARROT(MC.V_1_8),
    GOLDEN_CHESTPLATE(MC.V_1_8, "GOLD_CHESTPLATE"),
    GOLDEN_HELMET(MC.V_1_8, "GOLD_HELMET"),
    GOLDEN_HOE(MC.V_1_8, "GOLD_HOE"),
    GOLDEN_HORSE_ARMOR(MC.V_1_8, "GOLD_BARDING"),
    GOLDEN_LEGGINGS(MC.V_1_8, "GOLD_LEGGINGS"),
    GOLDEN_NAUTILUS_ARMOR(MC.V_1_21_11),
    GOLDEN_PICKAXE(MC.V_1_8, "GOLD_PICKAXE"),
    GOLDEN_SHOVEL(MC.V_1_8, "GOLD_SPADE"),
    GOLDEN_SPEAR(MC.V_1_21_11),
    GOLDEN_SWORD(MC.V_1_8, "GOLD_SWORD"),
    GOLD_BLOCK(MC.V_1_8),
    GOLD_INGOT(MC.V_1_8),
    GOLD_NUGGET(MC.V_1_8),
    GOLD_ORE(MC.V_1_8),
    GRANITE(MC.V_1_13, "STONE:1", MC.V_1_8),
    GRANITE_SLAB(MC.V_1_14),
    GRANITE_STAIRS(MC.V_1_14),
    GRANITE_WALL(MC.V_1_14),
    //    1.12         1.13
    // GRASS     -> GRASS_BLOCK
    GRASS_BLOCK(MC.V_1_13, "GRASS", MC.V_1_8),
    GRAVEL(MC.V_1_8),
    GRAY_BANNER(MC.V_1_13, "BANNER:8", MC.V_1_8),
    GRAY_BED(MC.V_1_13, "BED:7", MC.V_1_12),
    GRAY_BUNDLE(MC.V_1_21_2),
    GRAY_CANDLE(MC.V_1_17),
    GRAY_CARPET(MC.V_1_13, "CARPET:7", MC.V_1_8),
    GRAY_CONCRETE(MC.V_1_13, "CONCRETE:7", MC.V_1_12),
    GRAY_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:7", MC.V_1_12),
    GRAY_DYE(MC.V_1_13, "DYE:8", MC.V_1_8, "INK_SACK"),
    GRAY_GLAZED_TERRACOTTA(MC.V_1_12),
    GRAY_HARNESS(MC.V_1_21_6),
    GRAY_SHULKER_BOX(MC.V_1_11),
    GRAY_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:7", MC.V_1_8),
    GRAY_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:7", MC.V_1_8),
    GRAY_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:7", MC.V_1_8, "STAINED_CLAY"),
    GRAY_WOOL(MC.V_1_13, "WOOL:7", MC.V_1_8),
    GREEN_BANNER(MC.V_1_13, "BANNER:2", MC.V_1_8),
    GREEN_BED(MC.V_1_13, "BED:13", MC.V_1_12),
    GREEN_BUNDLE(MC.V_1_21_2),
    GREEN_CANDLE(MC.V_1_17),
    GREEN_CARPET(MC.V_1_13, "CARPET:13", MC.V_1_8),
    GREEN_CONCRETE(MC.V_1_13, "CONCRETE:13", MC.V_1_12),
    GREEN_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:13", MC.V_1_12),
    GREEN_DYE(MC.V_1_14, "CACTUS_GREEN", MC.V_1_13, "DYE:2", MC.V_1_8, "INK_SACK"),
    GREEN_GLAZED_TERRACOTTA(MC.V_1_12),
    GREEN_HARNESS(MC.V_1_21_6),
    GREEN_SHULKER_BOX(MC.V_1_11),
    GREEN_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:13", MC.V_1_8),
    GREEN_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:13", MC.V_1_8),
    GREEN_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:13", MC.V_1_8, "STAINED_CLAY"),
    GREEN_WOOL(MC.V_1_13, "WOOL:13", MC.V_1_8),
    GRINDSTONE(MC.V_1_14),
    GUARDIAN_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Guardian", MC.V_1_9, "SPAWN_EGG:68", MC.V_1_8, "MONSTER_EGG"),
    GUNPOWDER(MC.V_1_8, "SULPHUR"),
    GUSTER_BANNER_PATTERN(MC.V_1_20_5),
    GUSTER_POTTERY_SHERD(MC.V_1_20_5),
    HANGING_ROOTS(MC.V_1_17),
    HAPPY_GHAST_SPAWN_EGG(MC.V_1_21_6),
    HAY_BLOCK(MC.V_1_8),
    HEARTBREAK_POTTERY_SHERD(MC.V_1_20),
    HEART_OF_THE_SEA(MC.V_1_13),
    HEART_POTTERY_SHERD(MC.V_1_20),
    HEAVY_CORE(MC.V_1_20_5),
    HEAVY_WEIGHTED_PRESSURE_PLATE(MC.V_1_8, "IRON_PLATE"),
    HOGLIN_SPAWN_EGG(MC.V_1_16),
    HONEYCOMB(MC.V_1_15),
    HONEYCOMB_BLOCK(MC.V_1_15),
    HONEY_BLOCK(MC.V_1_15),
    HONEY_BOTTLE(MC.V_1_15),
    HOPPER(MC.V_1_8),
    HOPPER_MINECART(MC.V_1_8),
    HORN_CORAL(MC.V_1_13),
    HORN_CORAL_BLOCK(MC.V_1_13),
    HORN_CORAL_FAN(MC.V_1_13),
    HORSE_SPAWN_EGG(MC.V_1_13, Map.of("SPAWN_EGG=horse", MC.V_1_11, "SPAWN_EGG=EntityHorse", MC.V_1_9, "SPAWN_EGG:100", MC.V_1_8), "MONSTER_EGG"),
    HOST_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_20),
    HOWL_POTTERY_SHERD(MC.V_1_20),
    HUSK_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=husk", MC.V_1_11, "MONSTER_EGG"),
    ICE(MC.V_1_8),
    INFESTED_CHISELED_STONE_BRICKS(MC.V_1_13, "MONSTER_EGG:5", MC.V_1_8, "MONSTER_EGGS"),
    INFESTED_COBBLESTONE(MC.V_1_13, "MONSTER_EGG:1", MC.V_1_8, "MONSTER_EGGS"),
    INFESTED_CRACKED_STONE_BRICKS(MC.V_1_13, "MONSTER_EGG:4", MC.V_1_8, "MONSTER_EGGS"),
    INFESTED_DEEPSLATE(MC.V_1_17),
    INFESTED_MOSSY_STONE_BRICKS(MC.V_1_13, "MONSTER_EGG:3", MC.V_1_8, "MONSTER_EGGS"),
    INFESTED_STONE(MC.V_1_13, "MONSTER_EGG", MC.V_1_8, "MONSTER_EGGS"),
    INFESTED_STONE_BRICKS(MC.V_1_13, "MONSTER_EGG:2", MC.V_1_8, "MONSTER_EGGS"),
    INK_SAC(MC.V_1_13),
    IRON_AXE(MC.V_1_8),
    IRON_BARS(MC.V_1_8, "IRON_FENCE"),
    IRON_BLOCK(MC.V_1_8),
    IRON_BOOTS(MC.V_1_8),
    IRON_CHAIN(MC.V_1_21_9, "CHAIN", MC.V_1_16),
    IRON_CHESTPLATE(MC.V_1_8),
    IRON_DOOR(MC.V_1_8),
    IRON_GOLEM_SPAWN_EGG(MC.V_1_19_3),
    IRON_HELMET(MC.V_1_8),
    IRON_HOE(MC.V_1_8),
    IRON_HORSE_ARMOR(MC.V_1_8, "IRON_BARDING"),
    IRON_INGOT(MC.V_1_8),
    IRON_LEGGINGS(MC.V_1_8),
    IRON_NAUTILUS_ARMOR(MC.V_1_21_11),
    IRON_NUGGET(MC.V_1_11),
    IRON_ORE(MC.V_1_8),
    IRON_PICKAXE(MC.V_1_8),
    IRON_SHOVEL(MC.V_1_8, "IRON_SPADE"),
    IRON_SPEAR(MC.V_1_21_11),
    IRON_SWORD(MC.V_1_8),
    IRON_TRAPDOOR(MC.V_1_8),
    ITEM_FRAME(MC.V_1_8),
    // "JACK_O_LANTERN" is an alias on legacy versions
    JACK_O_LANTERN(MC.V_1_13, "LIT_PUMPKIN", MC.V_1_8),
    JIGSAW(MC.V_1_14),
    JUKEBOX(MC.V_1_8),
    JUNGLE_BOAT(MC.V_1_9, "BOAT_JUNGLE"),
    JUNGLE_BUTTON(MC.V_1_13),
    JUNGLE_CHEST_BOAT(MC.V_1_19),
    JUNGLE_DOOR(MC.V_1_8, "JUNGLE_DOOR_ITEM"),
    JUNGLE_FENCE(MC.V_1_8),
    JUNGLE_FENCE_GATE(MC.V_1_8),
    JUNGLE_HANGING_SIGN(MC.V_1_19_3),
    JUNGLE_LEAVES(MC.V_1_13, "LEAVES:3", MC.V_1_8),
    JUNGLE_LOG(MC.V_1_13, "LOG:3", MC.V_1_8),
    JUNGLE_PLANKS(MC.V_1_13, "PLANKS:3", MC.V_1_8, "WOOD"),
    JUNGLE_PRESSURE_PLATE(MC.V_1_13),
    JUNGLE_SAPLING(MC.V_1_13, "SAPLING:3", MC.V_1_8),
    JUNGLE_SHELF(MC.V_1_21_9),
    JUNGLE_SIGN(MC.V_1_14),
    JUNGLE_SLAB(MC.V_1_13, "WOODEN_SLAB:3", MC.V_1_8, "WOOD_STEP"),
    JUNGLE_STAIRS(MC.V_1_8, "JUNGLE_WOOD_STAIRS"),
    JUNGLE_TRAPDOOR(MC.V_1_13),
    JUNGLE_WOOD(MC.V_1_13, "LOG:15", MC.V_1_8),
    KELP(MC.V_1_13),
    KNOWLEDGE_BOOK(MC.V_1_12),
    LADDER(MC.V_1_8),
    LANTERN(MC.V_1_14),
    LAPIS_BLOCK(MC.V_1_8),
    LAPIS_LAZULI(MC.V_1_13),
    LAPIS_ORE(MC.V_1_8),
    LARGE_AMETHYST_BUD(MC.V_1_17),
    LARGE_FERN(MC.V_1_13, "DOUBLE_PLANT:3", MC.V_1_8),
    LAVA_BUCKET(MC.V_1_8),
    LEAD(MC.V_1_8, "LEASH"),
    LEAF_LITTER(MC.V_1_21_5),
    LEATHER(MC.V_1_8),
    LEATHER_BOOTS(MC.V_1_8),
    LEATHER_CHESTPLATE(MC.V_1_8),
    LEATHER_HELMET(MC.V_1_8),
    LEATHER_HORSE_ARMOR(MC.V_1_14),
    LEATHER_LEGGINGS(MC.V_1_8),
    LECTERN(MC.V_1_14),
    LEVER(MC.V_1_8),
    LIGHT(MC.V_1_17),
    LIGHTNING_ROD(MC.V_1_17),
    LIGHT_BLUE_BANNER(MC.V_1_13, "BANNER:12", MC.V_1_8),
    LIGHT_BLUE_BED(MC.V_1_13, "BED:3", MC.V_1_12),
    LIGHT_BLUE_BUNDLE(MC.V_1_21_2),
    LIGHT_BLUE_CANDLE(MC.V_1_17),
    LIGHT_BLUE_CARPET(MC.V_1_13, "CARPET:3", MC.V_1_8),
    LIGHT_BLUE_CONCRETE(MC.V_1_13, "CONCRETE:3", MC.V_1_12),
    LIGHT_BLUE_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:3", MC.V_1_12),
    LIGHT_BLUE_DYE(MC.V_1_13, "DYE:12", MC.V_1_8, "INK_SACK"),
    LIGHT_BLUE_GLAZED_TERRACOTTA(MC.V_1_12),
    LIGHT_BLUE_HARNESS(MC.V_1_21_6),
    LIGHT_BLUE_SHULKER_BOX(MC.V_1_11),
    LIGHT_BLUE_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:3", MC.V_1_8),
    LIGHT_BLUE_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:3", MC.V_1_8),
    LIGHT_BLUE_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:3", MC.V_1_8, "STAINED_CLAY"),
    LIGHT_BLUE_WOOL(MC.V_1_13, "WOOL:3", MC.V_1_8),
    LIGHT_GRAY_BANNER(MC.V_1_13, "BANNER:7", MC.V_1_8),
    LIGHT_GRAY_BED(MC.V_1_13, "BED:8", MC.V_1_12),
    LIGHT_GRAY_BUNDLE(MC.V_1_21_2),
    LIGHT_GRAY_CANDLE(MC.V_1_17),
    LIGHT_GRAY_CARPET(MC.V_1_13, "CARPET:8", MC.V_1_8),
    LIGHT_GRAY_CONCRETE(MC.V_1_13, "CONCRETE:8", MC.V_1_12),
    LIGHT_GRAY_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:8", MC.V_1_12),
    LIGHT_GRAY_DYE(MC.V_1_13, "DYE:7", MC.V_1_8, "INK_SACK"),
    LIGHT_GRAY_GLAZED_TERRACOTTA(MC.V_1_13, "SILVER_GLAZED_TERRACOTTA", MC.V_1_12),
    LIGHT_GRAY_HARNESS(MC.V_1_21_6),
    LIGHT_GRAY_SHULKER_BOX(MC.V_1_13, "SILVER_SHULKER_BOX", MC.V_1_11),
    LIGHT_GRAY_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:8", MC.V_1_8),
    LIGHT_GRAY_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:8", MC.V_1_8),
    LIGHT_GRAY_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:8", MC.V_1_8, "STAINED_CLAY"),
    LIGHT_GRAY_WOOL(MC.V_1_13, "WOOL:8", MC.V_1_8),
    LIGHT_WEIGHTED_PRESSURE_PLATE(MC.V_1_8, "GOLD_PLATE"),
    LILAC(MC.V_1_13, "DOUBLE_PLANT:1", MC.V_1_8),
    LILY_OF_THE_VALLEY(MC.V_1_14),
    LILY_PAD(MC.V_1_13, "WATERLILY", MC.V_1_8, "WATER_LILY"),
    LIME_BANNER(MC.V_1_13, "BANNER:10", MC.V_1_8),
    LIME_BED(MC.V_1_13, "BED:5", MC.V_1_12),
    LIME_BUNDLE(MC.V_1_21_2),
    LIME_CANDLE(MC.V_1_17),
    LIME_CARPET(MC.V_1_13, "CARPET:5", MC.V_1_8),
    LIME_CONCRETE(MC.V_1_13, "CONCRETE:5", MC.V_1_12),
    LIME_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:5", MC.V_1_12),
    LIME_DYE(MC.V_1_13, "DYE:10", MC.V_1_8, "INK_SACK"),
    LIME_GLAZED_TERRACOTTA(MC.V_1_12),
    LIME_HARNESS(MC.V_1_21_6),
    LIME_SHULKER_BOX(MC.V_1_11),
    LIME_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:5", MC.V_1_8),
    LIME_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:5", MC.V_1_8),
    LIME_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:5", MC.V_1_8, "STAINED_CLAY"),
    LIME_WOOL(MC.V_1_13, "WOOL:5", MC.V_1_8),
    LINGERING_POTION(MC.V_1_9),
    // Removed in 1.9
    // Information: https://minecraft.wiki/w/Furnace#Lit_furnace_%22item%22
    LIT_FURNACE(MC.V_1_8, "BURNING_FURNACE"),
    LLAMA_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=llama", MC.V_1_11, "MONSTER_EGG"),
    LODESTONE(MC.V_1_16),
    LOOM(MC.V_1_14),
    MACE(MC.V_1_20_5),
    MAGENTA_BANNER(MC.V_1_13, "BANNER:13", MC.V_1_8),
    MAGENTA_BED(MC.V_1_13, "BED:2", MC.V_1_12),
    MAGENTA_BUNDLE(MC.V_1_21_2),
    MAGENTA_CANDLE(MC.V_1_17),
    MAGENTA_CARPET(MC.V_1_13, "CARPET:2", MC.V_1_8),
    MAGENTA_CONCRETE(MC.V_1_13, "CONCRETE:2", MC.V_1_12),
    MAGENTA_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:2", MC.V_1_12),
    MAGENTA_DYE(MC.V_1_13, "DYE:13", MC.V_1_8, "INK_SACK"),
    MAGENTA_GLAZED_TERRACOTTA(MC.V_1_12),
    MAGENTA_HARNESS(MC.V_1_21_6),
    MAGENTA_SHULKER_BOX(MC.V_1_11),
    MAGENTA_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:2", MC.V_1_8),
    MAGENTA_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:2", MC.V_1_8),
    MAGENTA_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:2", MC.V_1_8, "STAINED_CLAY"),
    MAGENTA_WOOL(MC.V_1_13, "WOOL:2", MC.V_1_8),
    MAGMA_BLOCK(MC.V_1_13, "MAGMA", MC.V_1_10),
    MAGMA_CREAM(MC.V_1_8),
    MAGMA_CUBE_SPAWN_EGG(MC.V_1_13, Map.of("SPAWN_EGG=magma_cube", MC.V_1_11, "SPAWN_EGG=LavaSlime", MC.V_1_9, "SPAWN_EGG:62", MC.V_1_8), "MONSTER_EGG"),
    MANGROVE_BOAT(MC.V_1_19),
    MANGROVE_BUTTON(MC.V_1_19),
    MANGROVE_CHEST_BOAT(MC.V_1_19),
    MANGROVE_DOOR(MC.V_1_19),
    MANGROVE_FENCE(MC.V_1_19),
    MANGROVE_FENCE_GATE(MC.V_1_19),
    MANGROVE_HANGING_SIGN(MC.V_1_19_3),
    MANGROVE_LEAVES(MC.V_1_19),
    MANGROVE_LOG(MC.V_1_19),
    MANGROVE_PLANKS(MC.V_1_19),
    MANGROVE_PRESSURE_PLATE(MC.V_1_19),
    MANGROVE_PROPAGULE(MC.V_1_19),
    MANGROVE_ROOTS(MC.V_1_19),
    MANGROVE_SHELF(MC.V_1_21_9),
    MANGROVE_SIGN(MC.V_1_19),
    MANGROVE_SLAB(MC.V_1_19),
    MANGROVE_STAIRS(MC.V_1_19),
    MANGROVE_TRAPDOOR(MC.V_1_19),
    MANGROVE_WOOD(MC.V_1_19),
    MAP(MC.V_1_8, "EMPTY_MAP"),
    MEDIUM_AMETHYST_BUD(MC.V_1_17),
    //    1.12           1.13
    // MELON_BLOCK -> MELON
    // MELON       -> MELON_SLICE
    //
    // "MELON" exists in legacy versions
    MELON(MC.V_1_13, "MELON_BLOCK", MC.V_1_8),
    MELON_SEEDS(MC.V_1_8),
    MELON_SLICE(MC.V_1_13, "MELON", MC.V_1_8),
    MILK_BUCKET(MC.V_1_8),
    MINECART(MC.V_1_8),
    MINER_POTTERY_SHERD(MC.V_1_20),
    MOJANG_BANNER_PATTERN(MC.V_1_14),
    MOOSHROOM_SPAWN_EGG(MC.V_1_13, Map.of("SPAWN_EGG=mooshroom", MC.V_1_11, "SPAWN_EGG=MushroomCow", MC.V_1_9, "SPAWN_EGG:96", MC.V_1_8), "MONSTER_EGG"),
    MOSSY_COBBLESTONE(MC.V_1_8),
    MOSSY_COBBLESTONE_SLAB(MC.V_1_14),
    MOSSY_COBBLESTONE_STAIRS(MC.V_1_14),
    MOSSY_COBBLESTONE_WALL(MC.V_1_13, "COBBLESTONE_WALL:1", MC.V_1_8, "COBBLE_WALL"),
    MOSSY_STONE_BRICKS(MC.V_1_13, "STONEBRICK:1", MC.V_1_8, "SMOOTH_BRICK"),
    MOSSY_STONE_BRICK_SLAB(MC.V_1_14),
    MOSSY_STONE_BRICK_STAIRS(MC.V_1_14),
    MOSSY_STONE_BRICK_WALL(MC.V_1_14),
    MOSS_BLOCK(MC.V_1_17),
    MOSS_CARPET(MC.V_1_17),
    MOURNER_POTTERY_SHERD(MC.V_1_20),
    MUD(MC.V_1_19),
    MUDDY_MANGROVE_ROOTS(MC.V_1_19),
    MUD_BRICKS(MC.V_1_19),
    MUD_BRICK_SLAB(MC.V_1_19),
    MUD_BRICK_STAIRS(MC.V_1_19),
    MUD_BRICK_WALL(MC.V_1_19),
    MULE_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=mule", MC.V_1_11, "MONSTER_EGG"),
    MUSHROOM_STEM(MC.V_1_13, "BROWN_MUSHROOM_BLOCK:15", MC.V_1_8, "HUGE_MUSHROOM_1"),
    MUSHROOM_STEW(MC.V_1_8, "MUSHROOM_SOUP"),
    MUSIC_DISC_11(MC.V_1_13, "RECORD_11", MC.V_1_8),
    MUSIC_DISC_13(MC.V_1_13, "RECORD_13", MC.V_1_8, "GOLD_RECORD"),
    MUSIC_DISC_5(MC.V_1_19),
    MUSIC_DISC_BLOCKS(MC.V_1_13, "RECORD_BLOCKS", MC.V_1_8, "RECORD_3"),
    MUSIC_DISC_CAT(MC.V_1_13, "RECORD_CAT", MC.V_1_8, "GREEN_RECORD"),
    MUSIC_DISC_CHIRP(MC.V_1_13, "RECORD_CHIRP", MC.V_1_8, "RECORD_4"),
    MUSIC_DISC_CREATOR(MC.V_1_21),
    MUSIC_DISC_CREATOR_MUSIC_BOX(MC.V_1_21),
    MUSIC_DISC_FAR(MC.V_1_13, "RECORD_FAR", MC.V_1_8, "RECORD_5"),
    MUSIC_DISC_LAVA_CHICKEN(MC.V_1_21_7),
    MUSIC_DISC_MALL(MC.V_1_13, "RECORD_MALL", MC.V_1_8, "RECORD_6"),
    MUSIC_DISC_MELLOHI(MC.V_1_13, "RECORD_MELLOHI", MC.V_1_8, "RECORD_7"),
    MUSIC_DISC_OTHERSIDE(MC.V_1_18),
    MUSIC_DISC_PIGSTEP(MC.V_1_16),
    MUSIC_DISC_PRECIPICE(MC.V_1_21),
    MUSIC_DISC_RELIC(MC.V_1_20),
    MUSIC_DISC_STAL(MC.V_1_13, "RECORD_STAL", MC.V_1_8, "RECORD_8"),
    MUSIC_DISC_STRAD(MC.V_1_13, "RECORD_STRAD", MC.V_1_8, "RECORD_9"),
    MUSIC_DISC_TEARS(MC.V_1_21_6),
    MUSIC_DISC_WAIT(MC.V_1_13, "RECORD_WAIT", MC.V_1_8, "RECORD_12"),
    MUSIC_DISC_WARD(MC.V_1_13, "RECORD_WARD", MC.V_1_8, "RECORD_10"),
    MUTTON(MC.V_1_8),
    MYCELIUM(MC.V_1_8, "MYCEL"),
    NAME_TAG(MC.V_1_8),
    NAUTILUS_SHELL(MC.V_1_13),
    NAUTILUS_SPAWN_EGG(MC.V_1_21_11),
    NETHERITE_AXE(MC.V_1_16),
    NETHERITE_BLOCK(MC.V_1_16),
    NETHERITE_BOOTS(MC.V_1_16),
    NETHERITE_CHESTPLATE(MC.V_1_16),
    NETHERITE_HELMET(MC.V_1_16),
    NETHERITE_HOE(MC.V_1_16),
    NETHERITE_HORSE_ARMOR(MC.V_1_21_11),
    NETHERITE_INGOT(MC.V_1_16),
    NETHERITE_LEGGINGS(MC.V_1_16),
    NETHERITE_NAUTILUS_ARMOR(MC.V_1_21_11),
    NETHERITE_PICKAXE(MC.V_1_16),
    NETHERITE_SCRAP(MC.V_1_16),
    NETHERITE_SHOVEL(MC.V_1_16),
    NETHERITE_SPEAR(MC.V_1_21_11),
    NETHERITE_SWORD(MC.V_1_16),
    NETHERITE_UPGRADE_SMITHING_TEMPLATE(MC.V_1_19_4),
    NETHERRACK(MC.V_1_8),
    //     1.12            1.13
    // NETHER_BRICK -> NETHER_BRICKS
    // NETHERBRICK  -> NETHER_BRICK
    //
    // "NETHER_BRICK" exists in legacy versions
    NETHER_BRICK(MC.V_1_13, "NETHERBRICK", MC.V_1_8, "NETHER_BRICK_ITEM"),
    NETHER_BRICKS(MC.V_1_13, "NETHER_BRICK", MC.V_1_8 ),
    NETHER_BRICK_FENCE(MC.V_1_8, "NETHER_FENCE"),
    NETHER_BRICK_SLAB(MC.V_1_13, "STONE_SLAB:6", MC.V_1_8, "STEP"),
    NETHER_BRICK_STAIRS(MC.V_1_8),
    NETHER_BRICK_WALL(MC.V_1_14),
    NETHER_GOLD_ORE(MC.V_1_16),
    NETHER_QUARTZ_ORE(MC.V_1_13, "QUARTZ_ORE", MC.V_1_8),
    NETHER_SPROUTS(MC.V_1_16),
    NETHER_STAR(MC.V_1_8),
    NETHER_WART(MC.V_1_8, "NETHER_STALK"),
    NETHER_WART_BLOCK(MC.V_1_10),
    // "NOTE_BLOCK" is an alias on legacy versions
    NOTE_BLOCK(MC.V_1_13, "NOTEBLOCK", MC.V_1_8),
    OAK_BOAT(MC.V_1_13, "BOAT", MC.V_1_8),
    OAK_BUTTON(MC.V_1_13, "WOODEN_BUTTON", MC.V_1_8, "WOOD_BUTTON"),
    OAK_CHEST_BOAT(MC.V_1_19),
    OAK_DOOR(MC.V_1_13, "WOODEN_DOOR", MC.V_1_8, "WOOD_DOOR"),
    OAK_FENCE(MC.V_1_13, "FENCE", MC.V_1_8),
    OAK_FENCE_GATE(MC.V_1_13, "FENCE_GATE", MC.V_1_8),
    OAK_HANGING_SIGN(MC.V_1_19_3),
    OAK_LEAVES(MC.V_1_13, "LEAVES", MC.V_1_8),
    OAK_LOG(MC.V_1_13, "LOG", MC.V_1_8),
    OAK_PLANKS(MC.V_1_13, "PLANKS", MC.V_1_8, "WOOD"),
    OAK_PRESSURE_PLATE(MC.V_1_13, "WOODEN_PRESSURE_PLATE", MC.V_1_8, "WOOD_PLATE"),
    OAK_SAPLING(MC.V_1_13, "SAPLING", MC.V_1_8),
    OAK_SHELF(MC.V_1_21_9),
    OAK_SIGN(MC.V_1_14, "SIGN", MC.V_1_8),
    OAK_SLAB(MC.V_1_13, "WOODEN_SLAB", MC.V_1_8, "WOOD_STEP"),
    OAK_STAIRS(MC.V_1_8, "WOOD_STAIRS"),
    OAK_TRAPDOOR(MC.V_1_13, "TRAPDOOR", MC.V_1_8, "TRAP_DOOR"),
    OAK_WOOD(MC.V_1_13, "LOG:12", MC.V_1_8),
    OBSERVER(MC.V_1_11),
    OBSIDIAN(MC.V_1_8),
    OCELOT_SPAWN_EGG(MC.V_1_13, Map.of("SPAWN_EGG=ocelot", MC.V_1_11, "SPAWN_EGG=Ozelot", MC.V_1_9, "SPAWN_EGG:98", MC.V_1_8), "MONSTER_EGG"),
    OCHRE_FROGLIGHT(MC.V_1_19),
    OMINOUS_BOTTLE(MC.V_1_20_5),
    OMINOUS_TRIAL_KEY(MC.V_1_20_5),
    OPEN_EYEBLOSSOM(MC.V_1_21_4),
    ORANGE_BANNER(MC.V_1_13, "BANNER:14", MC.V_1_8),
    ORANGE_BED(MC.V_1_13, "BED:1", MC.V_1_12),
    ORANGE_BUNDLE(MC.V_1_21_2),
    ORANGE_CANDLE(MC.V_1_17),
    ORANGE_CARPET(MC.V_1_13, "CARPET:1", MC.V_1_8),
    ORANGE_CONCRETE(MC.V_1_13, "CONCRETE:1", MC.V_1_12),
    ORANGE_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:1", MC.V_1_12),
    ORANGE_DYE(MC.V_1_13, "DYE:14", MC.V_1_8, "INK_SACK"),
    ORANGE_GLAZED_TERRACOTTA(MC.V_1_12),
    ORANGE_HARNESS(MC.V_1_21_6),
    ORANGE_SHULKER_BOX(MC.V_1_11),
    ORANGE_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:1", MC.V_1_8),
    ORANGE_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:1", MC.V_1_8),
    ORANGE_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:1", MC.V_1_8, "STAINED_CLAY"),
    ORANGE_TULIP(MC.V_1_13, "RED_FLOWER:5", MC.V_1_8, "RED_ROSE"),
    ORANGE_WOOL(MC.V_1_13, "WOOL:1", MC.V_1_8),
    OXEYE_DAISY(MC.V_1_13, "RED_FLOWER:8", MC.V_1_8, "RED_ROSE"),
    OXIDIZED_CHISELED_COPPER(MC.V_1_20_3),
    OXIDIZED_COPPER(MC.V_1_17),
    OXIDIZED_COPPER_BARS(MC.V_1_21_9),
    OXIDIZED_COPPER_BULB(MC.V_1_20_3),
    OXIDIZED_COPPER_CHAIN(MC.V_1_21_9),
    OXIDIZED_COPPER_CHEST(MC.V_1_21_9),
    OXIDIZED_COPPER_DOOR(MC.V_1_20_3),
    OXIDIZED_COPPER_GOLEM_STATUE(MC.V_1_21_9),
    OXIDIZED_COPPER_GRATE(MC.V_1_20_3),
    OXIDIZED_COPPER_LANTERN(MC.V_1_21_9),
    OXIDIZED_COPPER_TRAPDOOR(MC.V_1_20_3),
    OXIDIZED_CUT_COPPER(MC.V_1_17),
    OXIDIZED_CUT_COPPER_SLAB(MC.V_1_17),
    OXIDIZED_CUT_COPPER_STAIRS(MC.V_1_17),
    OXIDIZED_LIGHTNING_ROD(MC.V_1_21_9),
    PACKED_ICE(MC.V_1_8),
    PACKED_MUD(MC.V_1_19),
    PAINTING(MC.V_1_8),
    PALE_HANGING_MOSS(MC.V_1_21_2),
    PALE_MOSS_BLOCK(MC.V_1_21_2),
    PALE_MOSS_CARPET(MC.V_1_21_2),
    PALE_OAK_BOAT(MC.V_1_21_2),
    PALE_OAK_BUTTON(MC.V_1_21_2),
    PALE_OAK_CHEST_BOAT(MC.V_1_21_2),
    PALE_OAK_DOOR(MC.V_1_21_2),
    PALE_OAK_FENCE(MC.V_1_21_2),
    PALE_OAK_FENCE_GATE(MC.V_1_21_2),
    PALE_OAK_HANGING_SIGN(MC.V_1_21_2),
    PALE_OAK_LEAVES(MC.V_1_21_2),
    PALE_OAK_LOG(MC.V_1_21_2),
    PALE_OAK_PLANKS(MC.V_1_21_2),
    PALE_OAK_PRESSURE_PLATE(MC.V_1_21_2),
    PALE_OAK_SAPLING(MC.V_1_21_2),
    PALE_OAK_SHELF(MC.V_1_21_9),
    PALE_OAK_SIGN(MC.V_1_21_2),
    PALE_OAK_SLAB(MC.V_1_21_2),
    PALE_OAK_STAIRS(MC.V_1_21_2),
    PALE_OAK_TRAPDOOR(MC.V_1_21_2),
    PALE_OAK_WOOD(MC.V_1_21_2),
    PANDA_SPAWN_EGG(MC.V_1_14),
    PAPER(MC.V_1_8),
    PARCHED_SPAWN_EGG(MC.V_1_21_11),
    PARROT_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=parrot", MC.V_1_12, "MONSTER_EGG"),
    PEARLESCENT_FROGLIGHT(MC.V_1_19),
    PEONY(MC.V_1_13, "DOUBLE_PLANT:5", MC.V_1_8),
    PETRIFIED_OAK_SLAB(MC.V_1_13),
    PHANTOM_MEMBRANE(MC.V_1_13),
    PHANTOM_SPAWN_EGG(MC.V_1_13),
    PIGLIN_BANNER_PATTERN(MC.V_1_16),
    PIGLIN_BRUTE_SPAWN_EGG(MC.V_1_16),
    PIGLIN_HEAD(MC.V_1_19_3),
    PIGLIN_SPAWN_EGG(MC.V_1_16),
    PIG_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Pig", MC.V_1_9, "SPAWN_EGG:90", MC.V_1_8, "MONSTER_EGG"),
    PILLAGER_SPAWN_EGG(MC.V_1_14),
    PINK_BANNER(MC.V_1_13, "BANNER:9", MC.V_1_8),
    PINK_BED(MC.V_1_13, "BED:6", MC.V_1_12),
    PINK_BUNDLE(MC.V_1_21_2),
    PINK_CANDLE(MC.V_1_17),
    PINK_CARPET(MC.V_1_13, "CARPET:6", MC.V_1_8),
    PINK_CONCRETE(MC.V_1_13, "CONCRETE:6", MC.V_1_12),
    PINK_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:6", MC.V_1_12),
    PINK_DYE(MC.V_1_13, "DYE:9", MC.V_1_8, "INK_SACK"),
    PINK_GLAZED_TERRACOTTA(MC.V_1_12),
    PINK_HARNESS(MC.V_1_21_6),
    PINK_PETALS(MC.V_1_19_4),
    PINK_SHULKER_BOX(MC.V_1_11),
    PINK_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:6", MC.V_1_8),
    PINK_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:6", MC.V_1_8),
    PINK_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:6", MC.V_1_8, "STAINED_CLAY"),
    PINK_TULIP(MC.V_1_13, "RED_FLOWER:7", MC.V_1_8, "RED_ROSE"),
    PINK_WOOL(MC.V_1_13, "WOOL:6", MC.V_1_8),
    PISTON(MC.V_1_8, "PISTON_BASE"),
    PITCHER_PLANT(MC.V_1_20),
    PITCHER_POD(MC.V_1_20),
    PLAYER_HEAD(MC.V_1_13, "SKULL:3", MC.V_1_8, "SKULL_ITEM"),
    PLENTY_POTTERY_SHERD(MC.V_1_20),
    PODZOL(MC.V_1_13, "DIRT:2", MC.V_1_8),
    POINTED_DRIPSTONE(MC.V_1_17),
    POISONOUS_POTATO(MC.V_1_8),
    POLAR_BEAR_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=polar_bear", MC.V_1_11, "SPAWN_EGG=PolarBear", MC.V_1_10, "MONSTER_EGG"),
    POLISHED_ANDESITE(MC.V_1_13, "STONE:6", MC.V_1_8),
    POLISHED_ANDESITE_SLAB(MC.V_1_14),
    POLISHED_ANDESITE_STAIRS(MC.V_1_14),
    POLISHED_BASALT(MC.V_1_16),
    POLISHED_BLACKSTONE(MC.V_1_16),
    POLISHED_BLACKSTONE_BRICKS(MC.V_1_16),
    POLISHED_BLACKSTONE_BRICK_SLAB(MC.V_1_16),
    POLISHED_BLACKSTONE_BRICK_STAIRS(MC.V_1_16),
    POLISHED_BLACKSTONE_BRICK_WALL(MC.V_1_16),
    POLISHED_BLACKSTONE_BUTTON(MC.V_1_16),
    POLISHED_BLACKSTONE_PRESSURE_PLATE(MC.V_1_16),
    POLISHED_BLACKSTONE_SLAB(MC.V_1_16),
    POLISHED_BLACKSTONE_STAIRS(MC.V_1_16),
    POLISHED_BLACKSTONE_WALL(MC.V_1_16),
    POLISHED_DEEPSLATE(MC.V_1_17),
    POLISHED_DEEPSLATE_SLAB(MC.V_1_17),
    POLISHED_DEEPSLATE_STAIRS(MC.V_1_17),
    POLISHED_DEEPSLATE_WALL(MC.V_1_17),
    POLISHED_DIORITE(MC.V_1_13, "STONE:4", MC.V_1_8),
    POLISHED_DIORITE_SLAB(MC.V_1_14),
    POLISHED_DIORITE_STAIRS(MC.V_1_14),
    POLISHED_GRANITE(MC.V_1_13, "STONE:2", MC.V_1_8),
    POLISHED_GRANITE_SLAB(MC.V_1_14),
    POLISHED_GRANITE_STAIRS(MC.V_1_14),
    POLISHED_TUFF(MC.V_1_20_3),
    POLISHED_TUFF_SLAB(MC.V_1_20_3),
    POLISHED_TUFF_STAIRS(MC.V_1_20_3),
    POLISHED_TUFF_WALL(MC.V_1_20_3),
    POPPED_CHORUS_FRUIT(MC.V_1_13, "CHORUS_FRUIT_POPPED", MC.V_1_9),
    POPPY(MC.V_1_13, "RED_FLOWER", MC.V_1_8, "RED_ROSE"),
    PORKCHOP(MC.V_1_8, "PORK"),
    POTATO(MC.V_1_8, "POTATO_ITEM"),
    POTION(MC.V_1_8),
    POWDER_SNOW_BUCKET(MC.V_1_17),
    // "POWERED_RAIL" is an alias on legacy versions
    POWERED_RAIL(MC.V_1_13, "GOLDEN_RAIL", MC.V_1_8),
    PRISMARINE(MC.V_1_8),
    PRISMARINE_BRICKS(MC.V_1_13, "PRISMARINE:1", MC.V_1_8),
    PRISMARINE_BRICK_SLAB(MC.V_1_13),
    PRISMARINE_BRICK_STAIRS(MC.V_1_13),
    PRISMARINE_CRYSTALS(MC.V_1_8),
    PRISMARINE_SHARD(MC.V_1_8),
    PRISMARINE_SLAB(MC.V_1_13),
    PRISMARINE_STAIRS(MC.V_1_13),
    PRISMARINE_WALL(MC.V_1_14),
    PRIZE_POTTERY_SHERD(MC.V_1_20, "POTTERY_SHARD_PRIZE", MC.V_1_19_4),
    PUFFERFISH(MC.V_1_13, "FISH:3", MC.V_1_8, "RAW_FISH"),
    PUFFERFISH_BUCKET(MC.V_1_13),
    PUFFERFISH_SPAWN_EGG(MC.V_1_13),
    // "PUMPKIN" exists in legacy versions
    PUMPKIN(MC.V_1_13),
    PUMPKIN_PIE(MC.V_1_8),
    PUMPKIN_SEEDS(MC.V_1_8),
    PURPLE_BANNER(MC.V_1_13, "BANNER:5", MC.V_1_8),
    PURPLE_BED(MC.V_1_13, "BED:10", MC.V_1_12),
    PURPLE_BUNDLE(MC.V_1_21_2),
    PURPLE_CANDLE(MC.V_1_17),
    PURPLE_CARPET(MC.V_1_13, "CARPET:10", MC.V_1_8),
    PURPLE_CONCRETE(MC.V_1_13, "CONCRETE:10", MC.V_1_12),
    PURPLE_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:10", MC.V_1_12),
    PURPLE_DYE(MC.V_1_13, "DYE:5", MC.V_1_8, "INK_SACK"),
    PURPLE_GLAZED_TERRACOTTA(MC.V_1_12),
    PURPLE_HARNESS(MC.V_1_21_6),
    PURPLE_SHULKER_BOX(MC.V_1_11),
    PURPLE_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:10", MC.V_1_8),
    PURPLE_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:10", MC.V_1_8),
    PURPLE_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:10", MC.V_1_8, "STAINED_CLAY"),
    PURPLE_WOOL(MC.V_1_13, "WOOL:10", MC.V_1_8),
    PURPUR_BLOCK(MC.V_1_9),
    PURPUR_PILLAR(MC.V_1_9),
    PURPUR_SLAB(MC.V_1_9),
    PURPUR_STAIRS(MC.V_1_9),
    QUARTZ(MC.V_1_8),
    QUARTZ_BLOCK(MC.V_1_8),
    QUARTZ_BRICKS(MC.V_1_16),
    QUARTZ_PILLAR(MC.V_1_13, "QUARTZ_BLOCK:2", MC.V_1_8),
    QUARTZ_SLAB(MC.V_1_13, "STONE_SLAB:7", MC.V_1_8, "STEP"),
    QUARTZ_STAIRS(MC.V_1_8),
    RABBIT(MC.V_1_8),
    RABBIT_FOOT(MC.V_1_8),
    RABBIT_HIDE(MC.V_1_8),
    RABBIT_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Rabbit", MC.V_1_9, "SPAWN_EGG:101", MC.V_1_8, "MONSTER_EGG"),
    RABBIT_STEW(MC.V_1_8),
    RAIL(MC.V_1_8, "RAILS"),
    RAISER_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_20),
    RAVAGER_SPAWN_EGG(MC.V_1_14),
    RAW_COPPER(MC.V_1_17),
    RAW_COPPER_BLOCK(MC.V_1_17),
    RAW_GOLD(MC.V_1_17),
    RAW_GOLD_BLOCK(MC.V_1_17),
    RAW_IRON(MC.V_1_17),
    RAW_IRON_BLOCK(MC.V_1_17),
    RECOVERY_COMPASS(MC.V_1_19),
    REDSTONE(MC.V_1_8),
    REDSTONE_BLOCK(MC.V_1_8),
    REDSTONE_LAMP(MC.V_1_8, "REDSTONE_LAMP_OFF"),
    REDSTONE_ORE(MC.V_1_8),
    REDSTONE_TORCH(MC.V_1_8, "REDSTONE_TORCH_ON"),
    RED_BANNER(MC.V_1_13, "BANNER:1", MC.V_1_8),
    RED_BED(MC.V_1_13, "BED:14", MC.V_1_12, "BED", MC.V_1_8),
    RED_BUNDLE(MC.V_1_21_2),
    RED_CANDLE(MC.V_1_17),
    RED_CARPET(MC.V_1_13, "CARPET:14", MC.V_1_8),
    RED_CONCRETE(MC.V_1_13, "CONCRETE:14", MC.V_1_12),
    RED_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:14", MC.V_1_12),
    RED_DYE(MC.V_1_14, "ROSE_RED", MC.V_1_13, "DYE:1", MC.V_1_8, "INK_SACK"),
    RED_GLAZED_TERRACOTTA(MC.V_1_12),
    RED_HARNESS(MC.V_1_21_6),
    RED_MUSHROOM(MC.V_1_8),
    RED_MUSHROOM_BLOCK(MC.V_1_8, "HUGE_MUSHROOM_2"),
    RED_NETHER_BRICKS(MC.V_1_13, "RED_NETHER_BRICK", MC.V_1_10),
    RED_NETHER_BRICK_SLAB(MC.V_1_14),
    RED_NETHER_BRICK_STAIRS(MC.V_1_14),
    RED_NETHER_BRICK_WALL(MC.V_1_14),
    RED_SAND(MC.V_1_13, "SAND:1", MC.V_1_8),
    RED_SANDSTONE(MC.V_1_8),
    RED_SANDSTONE_SLAB(MC.V_1_13, "STONE_SLAB2", MC.V_1_8),
    RED_SANDSTONE_STAIRS(MC.V_1_8),
    RED_SANDSTONE_WALL(MC.V_1_14),
    RED_SHULKER_BOX(MC.V_1_11),
    RED_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:14", MC.V_1_8),
    RED_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:14", MC.V_1_8),
    RED_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:14", MC.V_1_8, "STAINED_CLAY"),
    RED_TULIP(MC.V_1_13, "RED_FLOWER:4", MC.V_1_8, "RED_ROSE"),
    RED_WOOL(MC.V_1_13, "WOOL:14", MC.V_1_8),
    REINFORCED_DEEPSLATE(MC.V_1_19),
    REPEATER(MC.V_1_8, "DIODE"),
    REPEATING_COMMAND_BLOCK(MC.V_1_9, "COMMAND_REPEATING"),
    RESIN_BLOCK(MC.V_1_21_4),
    RESIN_BRICK(MC.V_1_21_4),
    RESIN_BRICKS(MC.V_1_21_4),
    RESIN_BRICK_SLAB(MC.V_1_21_4),
    RESIN_BRICK_STAIRS(MC.V_1_21_4),
    RESIN_BRICK_WALL(MC.V_1_21_4),
    RESIN_CLUMP(MC.V_1_21_4),
    RESPAWN_ANCHOR(MC.V_1_16),
    RIB_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_19_4),
    ROOTED_DIRT(MC.V_1_17),
    ROSE_BUSH(MC.V_1_13, "DOUBLE_PLANT:4", MC.V_1_8),
    ROTTEN_FLESH(MC.V_1_8),
    SADDLE(MC.V_1_8),
    SALMON(MC.V_1_13, "FISH:1", MC.V_1_8, "RAW_FISH"),
    SALMON_BUCKET(MC.V_1_13),
    SALMON_SPAWN_EGG(MC.V_1_13),
    SAND(MC.V_1_8),
    SANDSTONE(MC.V_1_8),
    SANDSTONE_SLAB(MC.V_1_13, "STONE_SLAB:1", MC.V_1_8, "STEP"),
    SANDSTONE_STAIRS(MC.V_1_8),
    SANDSTONE_WALL(MC.V_1_14),
    SCAFFOLDING(MC.V_1_14),
    SCRAPE_POTTERY_SHERD(MC.V_1_20_5),
    SCULK(MC.V_1_19),
    SCULK_CATALYST(MC.V_1_19),
    SCULK_SENSOR(MC.V_1_17),
    SCULK_SHRIEKER(MC.V_1_19),
    SCULK_VEIN(MC.V_1_19),
    SEAGRASS(MC.V_1_13),
    SEA_LANTERN(MC.V_1_8),
    SEA_PICKLE(MC.V_1_13),
    SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_19_4),
    SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_20),
    SHEAF_POTTERY_SHERD(MC.V_1_20),
    SHEARS(MC.V_1_8),
    SHEEP_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Sheep", MC.V_1_9, "SPAWN_EGG:91", MC.V_1_8, "MONSTER_EGG"),
    SHELTER_POTTERY_SHERD(MC.V_1_20),
    SHIELD(MC.V_1_9),
    SHORT_DRY_GRASS(MC.V_1_21_5),
    //    1.12         1.13          1.20.3
    // TALLGRASS -> GRASS       -> SHORT_GRASS
    //
    // "GRASS" exists in legacy versions
    SHORT_GRASS(MC.V_1_20_3, "GRASS", MC.V_1_13, "TALLGRASS:1", MC.V_1_8, "LONG_GRASS"),
    SHROOMLIGHT(MC.V_1_16),
    SHULKER_BOX(MC.V_1_13),
    SHULKER_SHELL(MC.V_1_11),
    SHULKER_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Shulker", MC.V_1_9, "MONSTER_EGG"),
    SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_20),
    SILVERFISH_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Silverfish", MC.V_1_9, "SPAWN_EGG:60", MC.V_1_8, "MONSTER_EGG"),
    SKELETON_HORSE_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=skeleton_horse", MC.V_1_11, "MONSTER_EGG"),
    SKELETON_SKULL(MC.V_1_13, "SKULL", MC.V_1_8, "SKULL_ITEM"),
    SKELETON_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Skeleton", MC.V_1_9, "SPAWN_EGG:51", MC.V_1_8, "MONSTER_EGG"),
    SKULL_BANNER_PATTERN(MC.V_1_14),
    SKULL_POTTERY_SHERD(MC.V_1_20, "POTTERY_SHARD_SKULL", MC.V_1_19_4),
    SLIME_BALL(MC.V_1_8),
    // "SLIME_BLOCK" is an alias on legacy versions
    SLIME_BLOCK(MC.V_1_13, "SLIME", MC.V_1_8),
    SLIME_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Slime", MC.V_1_9, "SPAWN_EGG:55", MC.V_1_8, "MONSTER_EGG"),
    SMALL_AMETHYST_BUD(MC.V_1_17),
    SMALL_DRIPLEAF(MC.V_1_17),
    SMITHING_TABLE(MC.V_1_14),
    SMOKER(MC.V_1_14),
    SMOOTH_BASALT(MC.V_1_17),
    SMOOTH_QUARTZ(MC.V_1_13),
    SMOOTH_QUARTZ_SLAB(MC.V_1_14),
    SMOOTH_QUARTZ_STAIRS(MC.V_1_14),
    SMOOTH_RED_SANDSTONE(MC.V_1_13, "RED_SANDSTONE:2", MC.V_1_8),
    SMOOTH_RED_SANDSTONE_SLAB(MC.V_1_14),
    SMOOTH_RED_SANDSTONE_STAIRS(MC.V_1_14),
    SMOOTH_SANDSTONE(MC.V_1_13, "SANDSTONE:2", MC.V_1_8),
    SMOOTH_SANDSTONE_SLAB(MC.V_1_14),
    SMOOTH_SANDSTONE_STAIRS(MC.V_1_14),
    SMOOTH_STONE(MC.V_1_13),
    SMOOTH_STONE_SLAB(MC.V_1_14),
    SNIFFER_EGG(MC.V_1_20),
    SNIFFER_SPAWN_EGG(MC.V_1_19_4),
    SNORT_POTTERY_SHERD(MC.V_1_20),
    SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_19_4),
    //    1.12          1.13
    // SNOW       -> SNOW_BLOCK
    // SNOW_LAYER -> SNOW
    //
    // "SNOW" exists in legacy versions
    SNOW(MC.V_1_13, "SNOW_LAYER", MC.V_1_8),
    SNOWBALL(MC.V_1_8, "SNOW_BALL"),
    SNOW_BLOCK(MC.V_1_13, "SNOW", MC.V_1_8),
    SNOW_GOLEM_SPAWN_EGG(MC.V_1_19_3),
    SOUL_CAMPFIRE(MC.V_1_16),
    SOUL_LANTERN(MC.V_1_16),
    SOUL_SAND(MC.V_1_8),
    SOUL_SOIL(MC.V_1_16),
    SOUL_TORCH(MC.V_1_16),
    SPAWNER(MC.V_1_13, "MOB_SPAWNER", MC.V_1_8),
    SPECTRAL_ARROW(MC.V_1_9),
    SPIDER_EYE(MC.V_1_8),
    SPIDER_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Spider", MC.V_1_9, "SPAWN_EGG:52", MC.V_1_8, "MONSTER_EGG"),
    SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_19_4),
    SPLASH_POTION(MC.V_1_9),
    SPONGE(MC.V_1_8),
    SPORE_BLOSSOM(MC.V_1_17),
    SPRUCE_BOAT(MC.V_1_9, "BOAT_SPRUCE"),
    SPRUCE_BUTTON(MC.V_1_13),
    SPRUCE_CHEST_BOAT(MC.V_1_19),
    SPRUCE_DOOR(MC.V_1_8, "SPRUCE_DOOR_ITEM"),
    SPRUCE_FENCE(MC.V_1_8),
    SPRUCE_FENCE_GATE(MC.V_1_8),
    SPRUCE_HANGING_SIGN(MC.V_1_19_3),
    SPRUCE_LEAVES(MC.V_1_13, "LEAVES:1", MC.V_1_8),
    SPRUCE_LOG(MC.V_1_13, "LOG:1", MC.V_1_8),
    SPRUCE_PLANKS(MC.V_1_13, "PLANKS:1", MC.V_1_8, "WOOD"),
    SPRUCE_PRESSURE_PLATE(MC.V_1_13),
    SPRUCE_SAPLING(MC.V_1_13, "SAPLING:1", MC.V_1_8),
    SPRUCE_SHELF(MC.V_1_21_9),
    SPRUCE_SIGN(MC.V_1_14),
    SPRUCE_SLAB(MC.V_1_13, "WOODEN_SLAB:1", MC.V_1_8, "WOOD_STEP"),
    SPRUCE_STAIRS(MC.V_1_8, "SPRUCE_WOOD_STAIRS"),
    SPRUCE_TRAPDOOR(MC.V_1_13),
    SPRUCE_WOOD(MC.V_1_13, "LOG:13", MC.V_1_8),
    SPYGLASS(MC.V_1_17),
    SQUID_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Squid", MC.V_1_9, "SPAWN_EGG:94", MC.V_1_8, "MONSTER_EGG"),
    STICK(MC.V_1_8),
    STICKY_PISTON(MC.V_1_8, "PISTON_STICKY_BASE"),
    STONE(MC.V_1_8),
    STONECUTTER(MC.V_1_14),
    STONE_AXE(MC.V_1_8),
    STONE_BRICKS(MC.V_1_13, "STONEBRICK", MC.V_1_8, "SMOOTH_BRICK"),
    STONE_BRICK_SLAB(MC.V_1_13, "STONE_SLAB:5", MC.V_1_8, "STEP"),
    STONE_BRICK_STAIRS(MC.V_1_8, "SMOOTH_STAIRS"),
    STONE_BRICK_WALL(MC.V_1_14),
    STONE_BUTTON(MC.V_1_8),
    STONE_HOE(MC.V_1_8),
    STONE_PICKAXE(MC.V_1_8),
    STONE_PRESSURE_PLATE(MC.V_1_8, "STONE_PLATE"),
    STONE_SHOVEL(MC.V_1_8, "STONE_SPADE"),
    STONE_SLAB(MC.V_1_8, "STEP"),
    STONE_SPEAR(MC.V_1_21_11),
    STONE_STAIRS(MC.V_1_14),
    STONE_SWORD(MC.V_1_8),
    STRAY_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=stray", MC.V_1_11, "MONSTER_EGG"),
    STRIDER_SPAWN_EGG(MC.V_1_16),
    STRING(MC.V_1_8),
    STRIPPED_ACACIA_LOG(MC.V_1_13),
    STRIPPED_ACACIA_WOOD(MC.V_1_13),
    STRIPPED_BAMBOO_BLOCK(MC.V_1_19_3),
    STRIPPED_BIRCH_LOG(MC.V_1_13),
    STRIPPED_BIRCH_WOOD(MC.V_1_13),
    STRIPPED_CHERRY_LOG(MC.V_1_19_4),
    STRIPPED_CHERRY_WOOD(MC.V_1_19_4),
    STRIPPED_CRIMSON_HYPHAE(MC.V_1_16),
    STRIPPED_CRIMSON_STEM(MC.V_1_16),
    STRIPPED_DARK_OAK_LOG(MC.V_1_13),
    STRIPPED_DARK_OAK_WOOD(MC.V_1_13),
    STRIPPED_JUNGLE_LOG(MC.V_1_13),
    STRIPPED_JUNGLE_WOOD(MC.V_1_13),
    STRIPPED_MANGROVE_LOG(MC.V_1_19),
    STRIPPED_MANGROVE_WOOD(MC.V_1_19),
    STRIPPED_OAK_LOG(MC.V_1_13),
    STRIPPED_OAK_WOOD(MC.V_1_13),
    STRIPPED_PALE_OAK_LOG(MC.V_1_21_2),
    STRIPPED_PALE_OAK_WOOD(MC.V_1_21_2),
    STRIPPED_SPRUCE_LOG(MC.V_1_13),
    STRIPPED_SPRUCE_WOOD(MC.V_1_13),
    STRIPPED_WARPED_HYPHAE(MC.V_1_16),
    STRIPPED_WARPED_STEM(MC.V_1_16),
    STRUCTURE_BLOCK(MC.V_1_10),
    STRUCTURE_VOID(MC.V_1_10),
    SUGAR(MC.V_1_8),
    // "SUGAR_CANE" is an alias on legacy versions
    SUGAR_CANE(MC.V_1_13, "REEDS", MC.V_1_8),
    SUNFLOWER(MC.V_1_13, "DOUBLE_PLANT", MC.V_1_8),
    SUSPICIOUS_GRAVEL(MC.V_1_20),
    SUSPICIOUS_SAND(MC.V_1_19_4),
    SUSPICIOUS_STEW(MC.V_1_14),
    SWEET_BERRIES(MC.V_1_14),
    TADPOLE_BUCKET(MC.V_1_19),
    TADPOLE_SPAWN_EGG(MC.V_1_19),
    TALL_DRY_GRASS(MC.V_1_21_5),
    TALL_GRASS(MC.V_1_13, "DOUBLE_PLANT:2", MC.V_1_8),
    TARGET(MC.V_1_16),
    TERRACOTTA(MC.V_1_13, "HARDENED_CLAY", MC.V_1_8, "HARD_CLAY"),
    TEST_BLOCK(MC.V_1_21_5),
    TEST_INSTANCE_BLOCK(MC.V_1_21_5),
    TIDE_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_19_4),
    TINTED_GLASS(MC.V_1_17),
    TIPPED_ARROW(MC.V_1_9),
    TNT(MC.V_1_8),
    TNT_MINECART(MC.V_1_8, "EXPLOSIVE_MINECART"),
    TORCH(MC.V_1_8),
    TORCHFLOWER(MC.V_1_19_4),
    TORCHFLOWER_SEEDS(MC.V_1_19_4),
    TOTEM_OF_UNDYING(MC.V_1_11, "TOTEM"),
    TRADER_LLAMA_SPAWN_EGG(MC.V_1_14),
    TRAPPED_CHEST(MC.V_1_8),
    TRIAL_KEY(MC.V_1_20_3),
    TRIAL_SPAWNER(MC.V_1_20_3),
    TRIDENT(MC.V_1_13),
    TRIPWIRE_HOOK(MC.V_1_8),
    TROPICAL_FISH(MC.V_1_13, "FISH:2", MC.V_1_8, "RAW_FISH"),
    TROPICAL_FISH_BUCKET(MC.V_1_13),
    TROPICAL_FISH_SPAWN_EGG(MC.V_1_13),
    TUBE_CORAL(MC.V_1_13),
    TUBE_CORAL_BLOCK(MC.V_1_13),
    TUBE_CORAL_FAN(MC.V_1_13),
    TUFF(MC.V_1_17),
    TUFF_BRICKS(MC.V_1_20_3),
    TUFF_BRICK_SLAB(MC.V_1_20_3),
    TUFF_BRICK_STAIRS(MC.V_1_20_3),
    TUFF_BRICK_WALL(MC.V_1_20_3),
    TUFF_SLAB(MC.V_1_20_3),
    TUFF_STAIRS(MC.V_1_20_3),
    TUFF_WALL(MC.V_1_20_3),
    TURTLE_EGG(MC.V_1_13),
    TURTLE_HELMET(MC.V_1_13),
    TURTLE_SCUTE(MC.V_1_20_5, "SCUTE", MC.V_1_13),
    TURTLE_SPAWN_EGG(MC.V_1_13),
    TWISTING_VINES(MC.V_1_16),
    VAULT(MC.V_1_20_5),
    VERDANT_FROGLIGHT(MC.V_1_19),
    VEX_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_19_4),
    VEX_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=vex", MC.V_1_11, "MONSTER_EGG"),
    VILLAGER_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Villager", MC.V_1_9, "SPAWN_EGG:120", MC.V_1_8, "MONSTER_EGG"),
    VINDICATOR_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=vindication_illager", MC.V_1_11, "MONSTER_EGG"),
    VINE(MC.V_1_8),
    WANDERING_TRADER_SPAWN_EGG(MC.V_1_14),
    WARDEN_SPAWN_EGG(MC.V_1_19),
    WARD_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_19_4),
    WARPED_BUTTON(MC.V_1_16),
    WARPED_DOOR(MC.V_1_16),
    WARPED_FENCE(MC.V_1_16),
    WARPED_FENCE_GATE(MC.V_1_16),
    WARPED_FUNGUS(MC.V_1_16),
    WARPED_FUNGUS_ON_A_STICK(MC.V_1_16),
    WARPED_HANGING_SIGN(MC.V_1_19_3),
    WARPED_HYPHAE(MC.V_1_16),
    WARPED_NYLIUM(MC.V_1_16),
    WARPED_PLANKS(MC.V_1_16),
    WARPED_PRESSURE_PLATE(MC.V_1_16),
    WARPED_ROOTS(MC.V_1_16),
    WARPED_SHELF(MC.V_1_21_9),
    WARPED_SIGN(MC.V_1_16),
    WARPED_SLAB(MC.V_1_16),
    WARPED_STAIRS(MC.V_1_16),
    WARPED_STEM(MC.V_1_16),
    WARPED_TRAPDOOR(MC.V_1_16),
    WARPED_WART_BLOCK(MC.V_1_16),
    WATER_BUCKET(MC.V_1_8),
    WAXED_CHISELED_COPPER(MC.V_1_20_3),
    WAXED_COPPER_BARS(MC.V_1_21_9),
    WAXED_COPPER_BLOCK(MC.V_1_17),
    WAXED_COPPER_BULB(MC.V_1_20_3),
    WAXED_COPPER_CHAIN(MC.V_1_21_9),
    WAXED_COPPER_CHEST(MC.V_1_21_9),
    WAXED_COPPER_DOOR(MC.V_1_20_3),
    WAXED_COPPER_GOLEM_STATUE(MC.V_1_21_9),
    WAXED_COPPER_GRATE(MC.V_1_20_3),
    WAXED_COPPER_LANTERN(MC.V_1_21_9),
    WAXED_COPPER_TRAPDOOR(MC.V_1_20_3),
    WAXED_CUT_COPPER(MC.V_1_17),
    WAXED_CUT_COPPER_SLAB(MC.V_1_17),
    WAXED_CUT_COPPER_STAIRS(MC.V_1_17),
    WAXED_EXPOSED_CHISELED_COPPER(MC.V_1_20_3),
    WAXED_EXPOSED_COPPER(MC.V_1_17),
    WAXED_EXPOSED_COPPER_BARS(MC.V_1_21_9),
    WAXED_EXPOSED_COPPER_BULB(MC.V_1_20_3),
    WAXED_EXPOSED_COPPER_CHAIN(MC.V_1_21_9),
    WAXED_EXPOSED_COPPER_CHEST(MC.V_1_21_9),
    WAXED_EXPOSED_COPPER_DOOR(MC.V_1_20_3),
    WAXED_EXPOSED_COPPER_GOLEM_STATUE(MC.V_1_21_9),
    WAXED_EXPOSED_COPPER_GRATE(MC.V_1_20_3),
    WAXED_EXPOSED_COPPER_LANTERN(MC.V_1_21_9),
    WAXED_EXPOSED_COPPER_TRAPDOOR(MC.V_1_20_3),
    WAXED_EXPOSED_CUT_COPPER(MC.V_1_17),
    WAXED_EXPOSED_CUT_COPPER_SLAB(MC.V_1_17),
    WAXED_EXPOSED_CUT_COPPER_STAIRS(MC.V_1_17),
    WAXED_EXPOSED_LIGHTNING_ROD(MC.V_1_21_9),
    WAXED_LIGHTNING_ROD(MC.V_1_21_9),
    WAXED_OXIDIZED_CHISELED_COPPER(MC.V_1_20_3),
    WAXED_OXIDIZED_COPPER(MC.V_1_17),
    WAXED_OXIDIZED_COPPER_BARS(MC.V_1_21_9),
    WAXED_OXIDIZED_COPPER_BULB(MC.V_1_20_3),
    WAXED_OXIDIZED_COPPER_CHAIN(MC.V_1_21_9),
    WAXED_OXIDIZED_COPPER_CHEST(MC.V_1_21_9),
    WAXED_OXIDIZED_COPPER_DOOR(MC.V_1_20_3),
    WAXED_OXIDIZED_COPPER_GOLEM_STATUE(MC.V_1_21_9),
    WAXED_OXIDIZED_COPPER_GRATE(MC.V_1_20_3),
    WAXED_OXIDIZED_COPPER_LANTERN(MC.V_1_21_9),
    WAXED_OXIDIZED_COPPER_TRAPDOOR(MC.V_1_20_3),
    WAXED_OXIDIZED_CUT_COPPER(MC.V_1_17),
    WAXED_OXIDIZED_CUT_COPPER_SLAB(MC.V_1_17),
    WAXED_OXIDIZED_CUT_COPPER_STAIRS(MC.V_1_17),
    WAXED_OXIDIZED_LIGHTNING_ROD(MC.V_1_21_9),
    WAXED_WEATHERED_CHISELED_COPPER(MC.V_1_20_3),
    WAXED_WEATHERED_COPPER(MC.V_1_17),
    WAXED_WEATHERED_COPPER_BARS(MC.V_1_21_9),
    WAXED_WEATHERED_COPPER_BULB(MC.V_1_20_3),
    WAXED_WEATHERED_COPPER_CHAIN(MC.V_1_21_9),
    WAXED_WEATHERED_COPPER_CHEST(MC.V_1_21_9),
    WAXED_WEATHERED_COPPER_DOOR(MC.V_1_20_3),
    WAXED_WEATHERED_COPPER_GOLEM_STATUE(MC.V_1_21_9),
    WAXED_WEATHERED_COPPER_GRATE(MC.V_1_20_3),
    WAXED_WEATHERED_COPPER_LANTERN(MC.V_1_21_9),
    WAXED_WEATHERED_COPPER_TRAPDOOR(MC.V_1_20_3),
    WAXED_WEATHERED_CUT_COPPER(MC.V_1_17),
    WAXED_WEATHERED_CUT_COPPER_SLAB(MC.V_1_17),
    WAXED_WEATHERED_CUT_COPPER_STAIRS(MC.V_1_17),
    WAXED_WEATHERED_LIGHTNING_ROD(MC.V_1_21_9),
    WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_20),
    WEATHERED_CHISELED_COPPER(MC.V_1_20_3),
    WEATHERED_COPPER(MC.V_1_17),
    WEATHERED_COPPER_BARS(MC.V_1_21_9),
    WEATHERED_COPPER_BULB(MC.V_1_20_3),
    WEATHERED_COPPER_CHAIN(MC.V_1_21_9),
    WEATHERED_COPPER_CHEST(MC.V_1_21_9),
    WEATHERED_COPPER_DOOR(MC.V_1_20_3),
    WEATHERED_COPPER_GOLEM_STATUE(MC.V_1_21_9),
    WEATHERED_COPPER_GRATE(MC.V_1_20_3),
    WEATHERED_COPPER_LANTERN(MC.V_1_21_9),
    WEATHERED_COPPER_TRAPDOOR(MC.V_1_20_3),
    WEATHERED_CUT_COPPER(MC.V_1_17),
    WEATHERED_CUT_COPPER_SLAB(MC.V_1_17),
    WEATHERED_CUT_COPPER_STAIRS(MC.V_1_17),
    WEATHERED_LIGHTNING_ROD(MC.V_1_21_9),
    WEEPING_VINES(MC.V_1_16),
    WET_SPONGE(MC.V_1_13, "SPONGE:1", MC.V_1_8),
    WHEAT(MC.V_1_8),
    WHEAT_SEEDS(MC.V_1_8, "SEEDS"),
    WHITE_BANNER(MC.V_1_13, "BANNER:15", MC.V_1_8),
    WHITE_BED(MC.V_1_13, "BED", MC.V_1_12),
    WHITE_BUNDLE(MC.V_1_21_2),
    WHITE_CANDLE(MC.V_1_17),
    WHITE_CARPET(MC.V_1_13, "CARPET", MC.V_1_8),
    WHITE_CONCRETE(MC.V_1_13, "CONCRETE", MC.V_1_12),
    WHITE_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER", MC.V_1_12),
    WHITE_DYE(MC.V_1_14, "BONE_MEAL", MC.V_1_13, "DYE:15", MC.V_1_8, "INK_SACK"),
    WHITE_GLAZED_TERRACOTTA(MC.V_1_12),
    WHITE_HARNESS(MC.V_1_21_6),
    WHITE_SHULKER_BOX(MC.V_1_11),
    WHITE_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS", MC.V_1_8),
    WHITE_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE", MC.V_1_8),
    WHITE_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY", MC.V_1_8, "STAINED_CLAY"),
    WHITE_TULIP(MC.V_1_13, "RED_FLOWER:6", MC.V_1_8, "RED_ROSE"),
    WHITE_WOOL(MC.V_1_13, "WOOL", MC.V_1_8),
    WILDFLOWERS(MC.V_1_21_5),
    WILD_ARMOR_TRIM_SMITHING_TEMPLATE(MC.V_1_19_4),
    WIND_CHARGE(MC.V_1_20_5),
    WITCH_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Witch", MC.V_1_9, "SPAWN_EGG:66", MC.V_1_8, "MONSTER_EGG"),
    WITHER_ROSE(MC.V_1_14),
    WITHER_SKELETON_SKULL(MC.V_1_13, "SKULL:1", MC.V_1_8, "SKULL_ITEM"),
    WITHER_SKELETON_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=wither_skeleton", MC.V_1_11, "MONSTER_EGG"),
    WITHER_SPAWN_EGG(MC.V_1_19_3),
    WOLF_ARMOR(MC.V_1_20_5),
    WOLF_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Wolf", MC.V_1_9, "SPAWN_EGG:95", MC.V_1_8, "MONSTER_EGG"),
    WOODEN_AXE(MC.V_1_8, "WOOD_AXE"),
    WOODEN_HOE(MC.V_1_8, "WOOD_HOE"),
    WOODEN_PICKAXE(MC.V_1_8, "WOOD_PICKAXE"),
    WOODEN_SHOVEL(MC.V_1_8, "WOOD_SPADE"),
    WOODEN_SPEAR(MC.V_1_21_11),
    WOODEN_SWORD(MC.V_1_8, "WOOD_SWORD"),
    WRITABLE_BOOK(MC.V_1_8, "BOOK_AND_QUILL"),
    WRITTEN_BOOK(MC.V_1_8),
    YELLOW_BANNER(MC.V_1_13, "BANNER:11", MC.V_1_8),
    YELLOW_BED(MC.V_1_13, "BED:4", MC.V_1_12),
    YELLOW_BUNDLE(MC.V_1_21_2),
    YELLOW_CANDLE(MC.V_1_17),
    YELLOW_CARPET(MC.V_1_13, "CARPET:4", MC.V_1_8),
    YELLOW_CONCRETE(MC.V_1_13, "CONCRETE:4", MC.V_1_12),
    YELLOW_CONCRETE_POWDER(MC.V_1_13, "CONCRETE_POWDER:4", MC.V_1_12),
    YELLOW_DYE(MC.V_1_14, "DANDELION_YELLOW", MC.V_1_13, "DYE:11", MC.V_1_8, "INK_SACK"),
    YELLOW_GLAZED_TERRACOTTA(MC.V_1_12),
    YELLOW_HARNESS(MC.V_1_21_6),
    YELLOW_SHULKER_BOX(MC.V_1_11),
    YELLOW_STAINED_GLASS(MC.V_1_13, "STAINED_GLASS:4", MC.V_1_8),
    YELLOW_STAINED_GLASS_PANE(MC.V_1_13, "STAINED_GLASS_PANE:4", MC.V_1_8),
    YELLOW_TERRACOTTA(MC.V_1_13, "STAINED_HARDENED_CLAY:4", MC.V_1_8, "STAINED_CLAY"),
    YELLOW_WOOL(MC.V_1_13, "WOOL:4", MC.V_1_8),
    ZOGLIN_SPAWN_EGG(MC.V_1_16),
    ZOMBIE_HEAD(MC.V_1_13, "SKULL:2", MC.V_1_8, "SKULL_ITEM"),
    ZOMBIE_HORSE_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=zombie_horse", MC.V_1_11, "MONSTER_EGG"),
    ZOMBIE_NAUTILUS_SPAWN_EGG(MC.V_1_21_11),
    ZOMBIE_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=Zombie", MC.V_1_9, "SPAWN_EGG:54", MC.V_1_8, "MONSTER_EGG"),
    ZOMBIE_VILLAGER_SPAWN_EGG(MC.V_1_13, "SPAWN_EGG=zombie_villager", MC.V_1_11, "MONSTER_EGG"),
    ZOMBIFIED_PIGLIN_SPAWN_EGG(MC.V_1_16, Map.of("ZOMBIE_PIGMAN_SPAWN_EGG", MC.V_1_13, "SPAWN_EGG=zombie_pigman", MC.V_1_11, "SPAWN_EGG=PigZombie", MC.V_1_9, "SPAWN_EGG:57", MC.V_1_8), "MONSTER_EGG");

    /**
     * Cached values of {@link ItemMaterialTag#values()}
     */
    public static final ItemMaterialTag[] VALUES = values();
    /**
     * Cached values of {@link ItemMaterialTag#values()} including
     * only server version compatible materials.
     */
    public static final Map<String, ItemMaterialTag> SERVER_VALUES;

    static {
        final Map<String, ItemMaterialTag> compatible = new HashMap<>();
        for (ItemMaterialTag tag : VALUES) {
            final TreeMap<MC, Data> names = tag.getDataMap();
            // Fix legacy SPAWN_EGG entity name for MC 1.11 & 1.12
            if (tag.name().contains("SPAWN_EGG") && names.size() > 1) {
                final MC version = names.containsKey(MC.V_1_11) ? MC.V_1_11 : names.containsKey(MC.V_1_10) ? MC.V_1_10 : names.containsKey(MC.V_1_9) ? MC.V_1_9 : null;
                if (version != null) {
                    String entity = names.get(version).entity().toLowerCase();
                    names.put(MC.V_1_11, Data.valueOf("SPAWN_EGG=minecraft:" + entity));
                    names.put(MC.V_1_12, Data.valueOf("SPAWN_EGG=" + entity));
                }
            }
            final Data name = tag.getData();
            if (name != null) {
                compatible.put(name.id(), tag);
            }
        }
        SERVER_VALUES = compatible;
    }

    private final TreeMap<MC, Data> dataMap;
    private final String[] aliases;

    @Deprecated(since = "1.5.14", forRemoval = true)
    private TreeMap<Float, String> names;

    /**
     * Change material name case without affecting entity ID (if contains it).
     *
     * @param name  Material name.
     * @param upper True for uppercase.
     * @return A material name.
     */
    @NotNull
    public static String changeNameCase(@NotNull String name, boolean upper) {
        String finalName = upper ? name.toUpperCase() : name.toLowerCase();
        if (name.contains("=")) {
            return finalName.split("=", 2)[0] + "=" + name.split("=", 2)[1];
        }
        return finalName;
    }

    ItemMaterialTag(@NotNull MC version, @NotNull String name1, @NotNull MC ver1, @NotNull String name2, @NotNull MC ver2, @NotNull String... aliases) {
        this(version, Map.of(name1, ver1, name2, ver2), aliases);
    }

    ItemMaterialTag(@NotNull MC version, @NotNull String name1, @NotNull MC ver1, @NotNull String... aliases) {
        this(version, Map.of(name1, ver1), aliases);
    }

    ItemMaterialTag(@NotNull MC version, @NotNull String... aliases) {
        this.dataMap = new TreeMap<>();
        dataMap.put(version, Data.valueOf(this.name()));
        this.aliases = aliases;
    }

    ItemMaterialTag(@NotNull MC version, @NotNull Map<String, MC> names, @NotNull String... aliases) {
        this.dataMap = new TreeMap<>();
        this.dataMap.put(version, Data.valueOf(this.name()));
        names.forEach((name, ver) -> this.dataMap.put(ver, Data.valueOf(name)));
        this.aliases = aliases;
    }

    /**
     * Get current material data based on current minecraft version.
     *
     * @return material data or null if not found.
     */
    @Nullable
    @ApiStatus.Experimental
    public Data getData() {
        return getDataFor(MC.version());
    }

    /**
     * Get current map containing material data based on minecraft versions.
     *
     * @return a TreeMap with material data.
     */
    @NotNull
    public TreeMap<MC, Data> getDataMap() {
        return dataMap;
    }

    /**
     * Get current material data for provided server version or null if the required material cannot be found.
     *
     * @param serverVersion the server version to check.
     * @return              a material data or null.
     */
    @Nullable
    @ApiStatus.Experimental
    public Data getDataFor(@NotNull MC serverVersion) {
        for (MC version : dataMap.descendingKeySet()) {
            // Found valid version
            if (version.isOlderThanOrEquals(serverVersion)) {
                final Data data = dataMap.get(version);
                // Find valid material using minecraft names as aliases
                for (Data name : dataMap.values()) {
                    if (name.bukkitMaterial().isPresent()) {
                        return data;
                    }
                }
                // Find valid material using aliases
                for (String alias : aliases) {
                    if (Material.getMaterial(alias) != null) {
                        return data;
                    }
                }
                // There's not a valid material found (Maybe Rtag version is too old for the current server?)
                break;
            }
        }
        return null;
    }

    /**
     * Get current material aliases.
     *
     * @return an array of material aliases.
     */
    @NotNull
    public String[] getAliases() {
        return aliases;
    }

    /**
     * Checks if this ItemMaterialTag is valid for current server version
     * by trying to find an existing Bukkit {@link Material}.
     *
     * @return true if is valid.
     */
    public boolean isValid() {
        return getDataFor(MC.version()) != null;
    }

    /**
     * Checks if this ItemMaterialTag is valid for provided server version
     * by trying to find an existing Bukkit {@link Material}.
     *
     * @param version the server version to check.
     * @return        true if is valid.
     */
    public boolean isValid(@NotNull MC version) {
        return getDataFor(version) != null;
    }

    /**
     * Get current map with material names and version.
     *
     * @return A TreeMap with material names.
     *
     * @deprecated use {@link #getDataMap()} instead.
     */
    @NotNull
    @Deprecated(since = "1.5.14")
    public TreeMap<Float, String> getNames() {
        if (names == null) {
            names = new TreeMap<>();
            for (Map.Entry<MC, Data> entry : dataMap.entrySet()) {
                names.put(entry.getKey().featRevision(), entry.getValue().formatted());
            }
        }
        return names;
    }

    /**
     * Get valid material name for current server version or null
     * if the required material cannot be found.
     *
     * @return A material name or null.
     *
     * @deprecated use {@link #getData()} instead.
     */
    @Nullable
    @Deprecated(since = "1.5.14")
    public String getValidMaterial() {
        final Data data = getDataFor(MC.version());
        return data == null ? null : data.formatted();
    }

    /**
     * Get value material name for provided server version or null
     * if the required material cannot be found.
     *
     * @param serverVersion The server version to check.
     * @return              A material name or null.
     *
     * @deprecated use {@link #getDataFor(MC)} instead.
     */
    @Deprecated(since = "1.5.14", forRemoval = true)
    @ApiStatus.ScheduledForRemoval(inVersion = "1.6.0")
    public String getValidMaterial(float serverVersion) {
        final Data data = getDataFor(MC.findReverse(MC::featRevision, serverVersion));
        return data == null ? null : data.formatted();
    }

    /**
     * Checks if this ItemMaterialTag is valid for provided server version
     * by trying to find an existing Bukkit {@link Material}.
     *
     * @param serverVersion The server version to check.
     * @return              True if is valid.
     *
     * @deprecated use {@link #isValid(MC)} instead.
     */
    @Deprecated(since = "1.5.14", forRemoval = true)
    @ApiStatus.ScheduledForRemoval(inVersion = "1.6.0")
    public boolean isValid(float serverVersion) {
        return getValidMaterial(serverVersion) != null;
    }

    /**
     * Data class that represent an item ID.
     */
    @ApiStatus.Experimental
    public static class Data {

        private static final Data EMPTY = new Data("", null, null) {
            @Override
            public boolean isEmpty() {
                return true;
            }
        };

        @NotNull
        public static Data empty() {
            return EMPTY;
        }

        @NotNull
        @ApiStatus.Internal
        public static Data valueOf(@Nullable String id) {
            if (id == null) {
                return empty();
            }

            String entity = null;
            if (id.contains("=")) {
                final int index = id.indexOf('=');
                entity = id.substring(index + 1);
                id = id.substring(0, index);
            }

            Short damage = null;
            if (id.contains(":")) {
                final int index = id.lastIndexOf(':');
                damage = Short.parseShort(id.substring(index + 1));
                id = id.substring(0, index);
            }

            if (id.isBlank()) {
                return empty();
            }

            return new Data((id.contains(":") ? "" : "minecraft:") + id.toLowerCase(), damage, entity);
        }

        private final String id;
        private final Short damage;
        private final String entity;

        private transient String formatted;
        @SuppressWarnings("all")
        private transient Optional<Material> bukkitMaterial;

        /**
         * Constructs a data instance with the given parameters.
         *
         * @param id     the item id.
         * @param damage the item damage value.
         * @param entity the entity id (for legacy spawn eggs).
         */
        public Data(@NotNull String id, @Nullable Short damage, @Nullable String entity) {
            this.id = id;
            this.damage = damage;
            this.entity = entity;
        }

        public boolean isEmpty() {
            return false;
        }

        /**
         * Get the item id.
         *
         * @return the item id.
         */
        @NotNull
        public String id() {
            return id;
        }

        /**
         * Get the item damage value.
         *
         * @return the item damage value.
         */
        @Nullable
        public Short damage() {
            return damage;
        }

        /**
         * Get the entity id (for legacy spawn eggs).
         *
         * @return the entity id.
         */
        @Nullable
        public String entity() {
            return entity;
        }

        /**
         * Get the formatted item id.
         *
         * @return the formatted item id.
         */
        @NotNull
        @ApiStatus.Internal
        public String formatted() {
            if (formatted == null) {
                final StringBuilder builder = new StringBuilder();
                builder.append((this.id.contains(":") ? this.id.split(":")[1] : this.id).toUpperCase());
                if (this.damage != null) {
                    builder.append(":").append(this.damage);
                }
                if (this.entity != null) {
                    builder.append("=").append(this.entity);
                }
                formatted = builder.toString();
            }
            return formatted;
        }

        /**
         * Get bukkit material representation of this material.
         *
         * @return the bukkit material representation or null.
         */
        @NotNull
        @ApiStatus.Internal
        @SuppressWarnings("all")
        public Optional<Material> bukkitMaterial() {
            if (bukkitMaterial == null) {
                bukkitMaterial = Optional.ofNullable(Material.getMaterial((id.contains(":") ? id.split(":")[1] : id).toUpperCase()));
            }
            return bukkitMaterial;
        }

        @NotNull
        public Data withDamage(@Nullable Short damage) {
            return new Data(this.id, damage, this.entity);
        }

        @NotNull
        public Data withEntity(@Nullable String entity) {
            return new Data(this.id, this.damage, entity);
        }

        @Override
        public String toString() {
            return this.id + (this.damage == null ? "" : ":" + this.damage) + (this.entity == null ? "" : "=" + this.entity);
        }

        @Override
        public final boolean equals(Object object) {
            if (!(object instanceof Data)) return false;

            Data data = (Data) object;
            return id.equals(data.id) && Objects.equals(damage, data.damage) && Objects.equals(entity, data.entity);
        }

        @Override
        public int hashCode() {
            int result = id.hashCode();
            result = 31 * result + Objects.hashCode(damage);
            result = 31 * result + Objects.hashCode(entity);
            return result;
        }
    }
}
