name: Java CI

on:
  push:
    branches: [ main ]
    paths:
      - 'rtag-*/**'
      - 'src/**'
      - 'build.gradle'
  pull_request:
    branches: [ main ]
    paths:
      - 'rtag-*/**'
      - 'src/**'
      - 'build.gradle'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
